try {
(function(a){a=a.tmntag=a.tmntag||{};a._config={};var b="newsarama.com",c="tomshardware.co.uk",d="space.com";a._config.GDPR_PII_CMP_LOAD_BOOST_DOMAINS=[b,c,d];a._config.GDPR_MINISTUB_FOR_NON_EU_USERS_DOMAIN_LIST=[b,c,d];a._config.TEST_RAMP_INDEX_DEFAULT_TIMEOUT_BEFORE_DFP=2E3;b="enabled";a._config.TEST_5_LOAD_INDEX_SWITCH=b;a._config.TEST_5_DISPATCH_RAMP_INDEX_SWITCH=b;a._config.TEST_3_DISPATCH_RAMP_INDEX_SWITCH=b;a._config.TEST_6_DISPATCH_RAMP_INDEX_SWITCH=b;a._config.RAMP_INDEX_TESTS={"newsarama.com":{active:true,
ranges:[{ratio:50,mode:"ramp",experimentId:"103"},{ratio:50,mode:"index",experimentId:"105",indexScriptSrc:"//js-sec.indexww.com/ht/p/188387-179661097277331.js",wrapperType:"auto"}]},"tomshardware.co.uk":{active:true,ranges:[{ratio:33,mode:"ramp",experimentId:"113"},{ratio:33,mode:"hybrid",experimentId:"114",indexScriptSrc:"//js-sec.indexww.com/ht/p/188387-76307275764346.js",wrapperType:"universal",divids:["bottom_banner","below_the_article","in_article","rightcol_top_anchor","rightcol_top","header_leaderboard",
"footer_leaderboard","in-content-1","in-content-2","mobile-anchor"]},{ratio:33,mode:"index",experimentId:"127",indexScriptSrc:"//js-sec.indexww.com/ht/p/188387-76307275764346.js",wrapperType:"universal",divids:["bottom_banner","below_the_article","in_article","rightcol_top_anchor","rightcol_top","header_leaderboard","footer_leaderboard","in-content-1","in-content-2","mobile-anchor"]}]},"space.com":{active:true,ranges:[{ratio:50,mode:"ramp",experimentId:"116"},{ratio:50,mode:"hybrid",experimentId:"115",
indexScriptSrc:"//js-sec.indexww.com/ht/p/188387-21334115066397.js",wrapperType:"universal",divids:["header_leaderboard","in-content-1","in-content-2","in-content-3","m-in-article-1","m-in-article-2","m-in-article-3","mid_top_mobile1","mobile-anchor","rightcol_bottom","rightcol_mid","rightcol_middle_anchor","rightcol_top","rightcol_top_anchor","m_mobile-anchor","m_in-content-1","m_in-content-2","m_in-content-3"]},{ratio:0,mode:"index",experimentId:"128",indexScriptSrc:"//js-sec.indexww.com/ht/p/188387-21334115066397.js",
wrapperType:"universal",divids:["header_leaderboard","in-content-1","in-content-2","in-content-3","m-in-article-1","m-in-article-2","m-in-article-3","mid_top_mobile1","mobile-anchor","rightcol_bottom","rightcol_mid","rightcol_middle_anchor","rightcol_top","rightcol_top_anchor","m_mobile-anchor","m_in-content-1","m_in-content-2","m_in-content-3"]}]}}})(window);
} catch (e) {
console.error(e);
}
!function(A,n){for(var l in n)A[l]=n[l]}(window,function(A){function n(g){if(l[g])return l[g].exports;var u=l[g]={i:g,l:!1,exports:{}};return A[g].call(u.exports,u,u.exports,n),u.l=!0,u.exports}var l={};return n.m=A,n.c=l,n.d=function(g,u,l){n.o(g,u)||Object.defineProperty(g,u,{enumerable:!0,get:l})},n.r=function(g){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(g,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(g,"__esModule",{value:!0})},n.t=function(g,u){if(1&u&&
(g=n(g)),8&u)return g;if(4&u&&"object"==typeof g&&g&&g.__esModule)return g;var l=Object.create(null);if(n.r(l),Object.defineProperty(l,"default",{enumerable:!0,value:g}),2&u&&"string"!=typeof g)for(var A in g)n.d(l,A,function(l){return g[l]}.bind(null,A));return l},n.n=function(g){var l=g&&g.__esModule?function(){return g.default}:function(){return g};return n.d(l,"a",l),l},n.o=function(g,l){return Object.prototype.hasOwnProperty.call(g,l)},n.p="",n(n.s=3)}({3:function(A,n){function l(a){return(l=
"function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"==typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a})(a)}var g,u,G,H,I,F,C,D,z;window.TMNAPI_VERSION="tmnhead-5.18.0",window.TMNTAG_VERSION="1.4",window.TMNTAGVIDEOREFRESH_VERSION="1.0vr",window.PREBID_TIMEOUT=200,window.VIDEO_REFRESH_TIMEOUT=3E3,window.googletag=window.googletag||{},googletag.cmd=googletag.cmd||[],String.prototype.endsWith||(String.prototype.endsWith=
function(a,b){return(void 0===b||b>this.length)&&(b=this.length),this.substring(b-a.length,b)===a}),String.prototype.startsWith||(String.prototype.startsWith=function(a,b){return b=b||0,this.substr(b,a.length)===a}),Array.prototype.find||Object.defineProperty(Array.prototype,"find",{value:function(a,b){if(null==this)throw new TypeError('"this" is null or not defined');var c=Object(this),d=c.length>>>0;if("function"!=typeof a)throw new TypeError("predicate must be a function");b=b;for(var e=0;e<d;){var f=
c[e];if(a.call(b,f,e,c))return f;e++}}}),"remove"in Element.prototype||(Element.prototype.remove=function(){this.parentNode&&this.parentNode.removeChild(this)}),"function"!=typeof Object.assign&&Object.defineProperty(Object,"assign",{value:function(a,b){if(null==a)throw new TypeError("Cannot convert undefined or null to object");for(var c=Object(a),d=1;d<arguments.length;d++){var e=arguments[d];if(null!=e)for(var f in e)Object.prototype.hasOwnProperty.call(e,f)&&(c[f]=e[f])}return c},writable:!0,
configurable:!0}),window.tmntag_updateAdUnitTiming=function(a){tmntag.timing&&tmntag.timing.startTag&&tmntag.timing.loadTag&&(tmntag.timing.adunits[a]=tmntag.timing.adunits[a]||[],tmntag.timing.adunits[a].push({adLoadTime:(new Date).getTime()-tmntag.timing.startTag,tagLoadTime:tmntag.timing.startTag-tmntag.timing.loadTag}))},window.tmntag_getAdUnitTiming=function(a){return tmntag.timing&&tmntag.timing.adunits&&tmntag.timing.adunits[a]?tmntag.timing.adunits[a][tmntag.timing.adunits[a].length-1]:{adLoadTime:0,
tagLoadTime:0}},window.uuidv4=function(){return"xxxxxxxxxxxx4xxxyxxxxxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;return("x"==a?b:3&b|8).toString(16)})},window.defuuid=uuidv4(),window.experimentId,window.disableRTBBidding=!1,window.indexScriptSrc,window.tmntag=window.tmntag||{},tmntag.cookies={},tmntag.cookies.get=function(a){a=("; "+document.cookie).split("; "+a+"=");if(2===a.length)return a.pop().split(";").shift()},tmntag.cookies.getAll=function(){return document.cookie.split("; ").reduce(function(a,
b){var c=b.indexOf("=");return a[b.substr(0,c)]=b.substr(c+1),a},{})},tmntag.cookies.set=function(a,b,c){var d=new Date;d.setTime(d.getTime()+1E3*c);c="expires="+d.toUTCString();document.cookie=a+"="+b+";"+c+";path=/"},tmntag._config=tmntag._config||{},tmntag.config=tmntag.config||{},tmntag.config.get=function(a,b){return tmntag._config[a]||b},window.tmntag_retrieveBidsFromIndex=function(a){window.headertag=window.headertag||{},window.headertag.cmd=window.headertag.cmd||[],window.headertag.cmd.push(function(){a=
a.filter(function(a){return document.getElementById(a)}).map(function(a){return{htSlotName:a.trim()}}),window.headertag.retrieveDemand(a,function(a){var b,d;window.tmntag_extraTargeting=(d={},(b=a)&&b.slot&&Object.keys(b.slot).forEach(function(a){d[a]=[],b.slot[a].forEach(function(b){Object.keys(b.targeting).forEach(function(c){1===b.targeting[c].length?d[a].push([c,b.targeting[c][0]]):d[a].push([c,b.targeting[c]])})})}),d),console.log("- RAMP - Saving extra targeting from Index [current time: "+
(new Date).getTime()+"]",JSON.stringify(window.tmntag_extraTargeting))})})},window.tmntag_getQueryStringValue=function(a){return decodeURIComponent(window.location.search.replace(new RegExp("^(?:.*[&\\?]"+encodeURIComponent(a).replace(/[\.\+\*]/g,"\\$&")+"(?:\\=([^&]*))?)?.*$","i"),"$1"))},window.tmntag_currentDomainIsInList=function(a){return!!a.find(function(a){return-1!==tmntag_getCurrentDomain().indexOf(a)})},window.tmntag_getDomainConfiguration=function(a){var b=tmntag.config.get("RAMP_INDEX_TESTS");
if(b)return b[Object.keys(b).find(function(b){return-1!==a.indexOf(b)})]},window.tmntag_getCurrentDomain=function(){return document.location.hostname},window.tmntag_getCurrentDomainConfiguration=function(){return tmntag_getDomainConfiguration(tmntag_getCurrentDomain())},window.tmntag_getForcedMode=function(){var a="forcemode",b=["ramp","index","hybrid"],c=tmntag_getQueryStringValue(a);-1===b.indexOf(c)&&(c=void 0);a=tmntag.cookies.get(a);return-1===b.indexOf(a)&&(a=void 0),c||a},window.tmntag_checkForcedMode=
function(a){var b=tmntag_getForcedMode();if(void 0===b)return!1;a=tmntag_getDomainConfiguration(a);return void 0!==a&&void 0!==a.ranges&&1===a.ranges.map(function(a){return a.mode}).filter(function(a){return a==b}).length},window.tmntag_shouldApplyTest=function(a){return tmntag_checkForcedMode(a)||tmntag_isTestActiveForDomain(a)},window.tmntag_validateIndexConfiguration=function(a){a=tmntag_getDomainConfiguration(a).ranges.find(function(a){return"index"===a.mode});if(!a)return!0;var b=a&&void 0!==
a.ratio&&a.indexScriptSrc&&a.experimentId&&a.wrapperType;return"universal"===a.wrapperType&&(b=b&&Array.isArray(a.divids)),b},window.tmntag_validateHybridConfiguration=function(a){a=tmntag_getDomainConfiguration(a).ranges.find(function(a){return"hybrid"===a.mode});return!a||a&&void 0!==a.ratio&&a.indexScriptSrc&&a.experimentId&&"universal"===a.wrapperType&&Array.isArray(a.divids)},window.tmntag_validateRampConfiguration=function(a){a=tmntag_getDomainConfiguration(a).ranges.find(function(a){return"ramp"===
a.mode});return!a||a&&void 0!==a.ratio&&a.experimentId},window.tmntag_injectScript=function(a,b){var c=document.createElement("script");c.async=!!b,c.type="text/javascript",c.src=a;(a=document.getElementsByTagName("script")[0]||document.getElementsByTagName("body")[0])&&a.parentNode.insertBefore(c,a)},window.tmntag_random=function(a){return Math.floor(Math.random()*a)},window.tmntag_randomIndexFromRanges=function(a){if(a.length){var b=[];a=a.reduce(function(a,c){return b.push(a+c),a+c},0);a=tmntag_random(a);
for(var c=0;a>=b[c];)c++;return c}},window.tmntag_getRandomModeConfiguration=function(){var a=tmntag_getCurrentDomainConfiguration(),b=a.ranges.map(function(a){return a.ratio}),b=tmntag_randomIndexFromRanges(b);return a.ranges[b]},window.tmntag_configIsValid=function(a){return tmntag_validateRampConfiguration(a)&&tmntag_validateIndexConfiguration(a)&&tmntag_validateHybridConfiguration(a)},window.tmntag_isTestActiveForDomain=function(a){var b=tmntag_getDomainConfiguration(a);return b&&b.active&&Array.isArray(b.ranges)&&
0<b.ranges.length&&tmntag_configIsValid(a)},window.tmntag_getModeConfiguration=function(){var a=tmntag_getCurrentDomainConfiguration(),b=tmntag_getForcedMode();return b&&a.ranges.find(function(a){return a.mode===b})||tmntag_getRandomModeConfiguration()},window.tmntag_testRampAndIndex=function(){var a;if(a=tmntag_shouldApplyTest(tmntag_getCurrentDomain())){{a=tmntag_getModeConfiguration();switch(window.experimentId=a.experimentId,a.mode){case "index":window.indexScriptSrc=a.indexScriptSrc,tmntag_il=
!1,disable_refresh=!1,window.disableRTBBidding=!0,console.log("- RAMP - Index Enabled + RAMP Disabled, experimentId "+experimentId),"universal"===a.wrapperType&&(window.indexLoaded=!0,tmntag_retrieveBidsFromIndex(a.divids));break;case "hybrid":window.indexScriptSrc=a.indexScriptSrc,tmntag_il=!1,disable_refresh=!1,console.log("- RAMP - Index Enabled + RAMP Enabled, experimentId "+experimentId),"universal"===a.wrapperType&&(window.indexLoaded=!0,tmntag_retrieveBidsFromIndex(a.divids));break;case "ramp":console.log("- RAMP - Index Disabled + RAMP Enabled, experimentId ".concat(a.experimentId))}a=
void 0}}a,window.indexScriptSrc&&tmntag_injectScript(indexScriptSrc,!0)},window.tmntag_disableRampAndIndexTests||tmntag_testRampAndIndex(),tmntag_injectScript("//www.googletagservices.com/tag/js/gpt.js",!0),function(a){function b(){if(!e){e=!0;for(var a=0;a<d.length;a++)d[a].fn.call(window,d[a].ctx);d=[]}}function c(){"complete"===document.readyState&&b()}a=window;var d=[],e=!1,f=!1;a.tmntag_ready=function(a,q){e?setTimeout(function(){a(q)},1):(d.push({fn:a,ctx:q}),"complete"===document.readyState||
!document.attachEvent&&"interactive"===document.readyState?setTimeout(b,1):f||(document.addEventListener?(document.addEventListener("DOMContentLoaded",b,!1),window.addEventListener("load",b,!1)):(document.attachEvent("onreadystatechange",c),window.attachEvent("onload",b)),f=!0))}}(),g=function(){for(var a=0;tmntagCache&&a<tmntagCache.length;a++)if(tmntagCache[a]&&tmntagCache[a].isMouseOver){var b=Math.floor(11E3*Math.random()),c="https:"==document.location.protocol?"https://":"http://",d=void 0!==
window.context&&window.context||!top.window.experiments?"":top.window.experiments,b=c+"ads2.servebom.com/event.js?t=CC&id="+(top.window.requestid?top.window.requestid:0)+"&bid=&cp=0&bdrid=&crid=&e="+d+"&ad=&r="+b;tmntag_injectScript(b,!1)}},window.addEventListener&&(window.addEventListener("blur",g),window.addEventListener("focusout",g),window.addEventListener("focus",function(){window.addEventListener("blur",g)})),window.tmntag_getAdUnit=function(a){for(var b=0;b<tmntag.a.length;b++)if(tmntag.a[b].d===
a)return tmntag.a[b];return!1},window.tmntag_timestamp=function(){var a=new Date,b=function(a){return a<=9?"0"+a:""+a},c=a.getDate(),d=a.getFullYear(),e=a.getMonth()+1,f=a.getHours(),k=a.getMinutes(),q=a.getSeconds();a.getMilliseconds();return d+"-"+b(e)+"-"+b(c)+" "+b(f)+":"+b(k)+":"+b(q)},window.tmntag_inIframe=function(){return top!==self},window.tmntag_IEVersion=function(){var a=-1;if("Microsoft Internet Explorer"==navigator.appName){var b=navigator.userAgent;null!=(new RegExp("MSIE ([0-9]{1,}[.0-9]{0,})")).exec(b)&&
(a=parseFloat(RegExp.$1))}return a},window.tmntag_isArray=function(a){return a.constructor===Array},window.tmntag_getAdunitFromCache=function(a){return tmntagCache.find(function(b){return b.div&&b.div===a})||null},window.tmntag_getAdunitWithPrefixFromCacheForClone=function(a,b){var c=tmntagCache.filter(function(b){return void 0!==b.div&&0===b.div.indexOf(a)});return 0!=c.length&&(b&&b.resetPosition?c[0]:c[c.length-1])},window.tmntag_registerMouseOver=function(a){var b=tmntag_getAdunitFromCache(a);
a=document.querySelector("#"+a+" iframe");b&&a&&(a.addEventListener("mouseover",function(){b.isMouseOver=!0}),a.addEventListener("mouseout",function(){b.isMouseOver=!1}))},window.tmntag_processInContent=function(a){var b=tmntag.getAdParameters(a,"incontent_css_selector");b&&MultipleIncontent(a,b,{position:tmntag.getAdParameters(a,"incontent_position"),repetitionMob:tmntag.getAdParameters(a,"incontent_limit_mobile"),repetitionDesk:tmntag.getAdParameters(a,"incontent_limit_desktop"),elementsFormula:tmntag.getAdParameters(a,
"incontent_elements_formula"),progressive:tmntag.getAdParameters(a,"incontent_progressive")})},window.tmntag_isInlineMarkup=function(a){return!!tmntag.instartlogicEnabled()||tmntag&&tmntag.markupsInfo&&tmntag.markupsInfo[a]&&tmntag.markupsInfo[a].inline},window.tmntag_inlineMarkup=function(a){var b=!1,c=tmntag_getAdunitFromCache(a);if(!c||!tmntag_isInlineMarkup(a))return b;tmntag_processInContent(a);var d=document.getElementById(a);if(!d)return b;var e=tmntag.markupsInfo[a];if(e&&c){c=a+"_tmntag_inline_";
(b=document.getElementById(c))&&d.removeChild(b);b=document.createElement("div");b.id=c,b.style.border="0pt none",b.style.display="inline-block",b.style.width=(e.width||0)+"px",b.style.height=(e.height||0)+"px",b.style.margin="0px",b.style.padding="0px";var f=e.iframe,c=tmntag.markups[a];if(c=c.replace(/'\r\n|\r|\n/gm,""),f||tmntag.instartlogicEnabled()){f=document.createElement("iframe");f.frameBorder=0,f.scrolling="no",f.marginwidth=0,f.marginheight=0,f.style.width=(e.width||0)+"px",f.style.height=
(e.height||0)+"px",f.style.border="0pt none",f.style.margin="0px 0 0",f.width=e.width||0,f.height=e.height||0,b.appendChild(f),d.appendChild(b);d='<!DOCTYPE html><body marginheight="0" marginwidth="0">'+c+"</body></html>";f.contentDocument.open(),f.contentDocument.write(d),f.contentDocument.close()}else b.innerHTML=c,d.appendChild(b);tmntag.onInlineAdunitRendered({divid:a,size:{width:e.width||0,height:e.height||0}}),b=!0}return b},window.tmntag_defineAdUnit=function(a){var b=tmntag_getAdunitFromCache(a);
void 0===b.adunitRule?1===b.refresh?(tmntag_defineSlot(a,{},!0),b.refresh=0):1!==tmntag.f&&(tmntag_defineSlot(a),tmntag_processInContent(a)):(1===b.refresh&&(tmntag_defineSlot(a,{},!0),b.refresh=0),tmntag.enableSingleRequest())},window.tmntag_setExtraTargetingInSlot=function(a){if(window.indexLoaded){console.log("- RAMP - Setting extra targeting",window.tmntag_extraTargeting);var b=a.getSlotElementId(),c=window.tmntag_extraTargeting;c&&c[b]&&(c[b].forEach(function(b){a.setTargeting(b[0],b[1])}),delete c[b]),
c&&0===Object.keys(c).length&&delete window.tmntag_extraTargeting}},window.tmntag_defineSlot=function(a,b,c){var d,e=tmntag_getAdUnit(a),f=tmntag_getAdunitFromCache(a);try{if(tmntag_isInlineMarkup(a))return tmntag_inlineMarkup(a),null}catch(q){return console&&console.error&&console.error(q),null}if(c)d=tmntag.slots[a];else{if(e.z)d=googletag.defineSlot(e.s,e.z,e.d).addService(googletag.pubads()),tmntag.ced&&d.setCollapseEmptyDiv(!0,!0);else{d=document.getElementById(e.d);d&&(d.style.height="0px"),
d=googletag.defineOutOfPageSlot(e.s,e.d).addService(googletag.pubads())}e.c&&d.addService(googletag.companionAds().setRefreshUnfilledSlots(e.c)),f&&void 0!==f.sizeMapping&&d.defineSizeMapping(f.sizeMapping),tmntag.slots[a]=d}if(b=b||e&&e.g)for(var k in b)b.hasOwnProperty(k)&&d.setTargeting(k,b[k]);if(void 0!==tmntag.adtargets){a=tmntag.adtargets[e.d];if(void 0!==a&&tmntag.localAdtargets&&void 0!==tmntag.localAdtargets[e.d])for(b=0;b<tmntag.localAdtargets[e.d].length;b++)a.push(tmntag.localAdtargets[e.d][b]);
c&&d&&d.clearTargeting();for(b=0;d&&void 0!==a&&b<a.length;b++)"_bd"===a[b][0]&&"deal"===a[b][1]&&(a[b][1]="bid"),"undefined"!=typeof tmntag_disablertb&&tmntag_disablertb&&"_br"===a[b][0]||d.setTargeting(a[b][0],a[b][1]);tmntag_setExtraTargetingInSlot(d)}return d},window.tmntag_setGptLoaded=function(){tmntag_gptloaded=!0},window.tmntag_clientDim=function(){try{return(window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth)+"x"+(window.innerHeight||document.documentElement.clientHeight||
document.body.clientHeight)}catch(a){console.error(a)}},window.tmntag_additionalExperiments=function(){return window.experimentId?[experimentId]:[]},window.tmntag_googleSlots=function(a){var b=[];return a.forEach(function(a){tmntag.slots[a]&&b.push(tmntag.slots[a])}),b},window.tmntag_autorefresh=function(a){if(tmntag.getAdParameters(a,"auto_refresh_enabled")&&void 0!==tmntag.slots[a]){var b=tmntag.slots[a].getTargetingMap()._bd;if(void 0!==b&&"none"==b){var c=tmntag_getAdunitFromCache(a),d=c.auto_refresh_count||
0,b=parseInt(tmntag.getAdParameters(a,"auto_refresh_limit"),10)||1,e=parseInt(tmntag.getAdParameters(a,"auto_refresh_delay"),10)||6E4;d!=b&&setTimeout(function(){tmntag_inview(a,20)&&(c.auto_refresh_count=d+1,console.log("-- RAMP -- autoref",a,c.auto_refresh_count),tmntag.refresh(a))},e)}}},window.tmntag_inview=function(a,b,c){if(b=b||0,c=c||"visible",null!==document.querySelector("#"+a)){var d=document.querySelector("#"+a).getBoundingClientRect(),e=Math.max(document.documentElement.clientHeight,
window.innerHeight);a=d.bottom-b<0;b=0<=d.top-e+b;return"above"===c?a:"below"===c?b:!a&&!b}},window.tmntag_topLocation=function(){try{return window.context&&window.context.location&&window.context.location.href?window.context.location.href:window.top.document.location.href}catch(a){return window.document.referrer}},window.tmntag_referrer=function(){try{return window.context&&window.context.referrer?window.context.referrer:window.top.document.referrer}catch(a){return""}},window.tmntag_supportsFlash=
function(){var a=1;try{if(navigator.mimeTypes&&0<navigator.mimeTypes.length){var b=navigator.mimeTypes["application/x-shockwave-flash"];b&&b.enabledPlugin&&(a=1)}else if("undefined"!=typeof ActiveXObject)try{new ActiveXObject("ShockwaveFlash.ShockwaveFlash.1");a=1}catch(c){}}catch(c){console&&console.error&&console.error(exception)}return a},window.tmntag_gptloaded=!1,window.tmntag_callbacks=new function(){this.callback=[],this.callback_executed=[],this.pushCallback=function(a,b){void 0!==b?this.callback.push({callback:a,
params:b}):this.callback.push({callback:a})},this.executeCallbacks=function(){var a=this.callback.length;if(0<a)for(var b=0;b<a;){var c=this.callback[0];void 0!==c.params?c.callback.apply(null,c.params):c.callback(),this.callback.splice(0,1),this.callback_executed.push(c),b++}}},window.tmntag_initialLoadDisabled=!1,window.tmntag_initialLoadDisabledMode=!1,window.tmntagCache=[],tmntag.cmd=tmntag.cmd||[],window.tmntagDisplayed={},tmntag.timing={},tmntag.timing.adunits={},tmntag.timing.start=(new Date).getTime(),
tmntag.sr=!0,tmntag.ced=!0,tmntag.a=[],tmntag.slots={},tmntag.l=encodeURIComponent(tmntag_topLocation().replace("%","")),tmntag.tt=encodeURIComponent(document.title?document.title.replace("|",""):""),tmntag.t=tmntag_timestamp(),tmntag.tz=Math.round((new Date).getTimezoneOffset()),tmntag.r=tmntag_clientDim(),tmntag.su=0,tmntag.fs=tmntag_supportsFlash(),tmntag.disabledAdunits=[],tmntag.disableDFPRefresh=!1,tmntag.onAdunitRenderedCallbackFunction=function(){},tmntag.video=tmntag.video||{},tmntag.video.settings=
{},tmntag.video.status={},tmntag.safeFunctionCall=function(a,b){return"function"==typeof window[a]?window[a].apply():b||""},tmntag.instartlogicEnabled=function(){return window.I11C&&1===window.I11C.Morph},tmntag.placementCustomID=function(a){tmntag.pc=a},tmntag.getAdParameters=function(a,b){return void 0===a?tmntag&&tmntag.adparams:void 0===b?tmntag&&tmntag.adparams&&tmntag.adparams[a]:tmntag&&tmntag.adparams&&tmntag.adparams[a]&&tmntag.adparams[a][b]},tmntag.placement=function(a){tmntag.p=a},tmntag.account=
function(a){a&&(a=a.replace(/\t|\s+/gm,"")),tmntag.s=a},window.tmntag_removeByAttrValue=function(a,b,c){for(var d=a.length-1;0<=d;d--){var e=a[d];e[b]&&e[b]===c&&a.splice(d,1)}},tmntag.adunit=function(a){if(!tmntag.disabledAdunits.find(function(b){return b===a.div})){var b=tmntag_getAdunitFromCache(a.div);if(b){for(prop in a)b[prop]=a[prop];a=b}b={};return a.account?b.s=a.account:tmntag.s&&(b.s=tmntag.s),a.sizes&&(b.z=a.sizes),a.div&&(b.d=a.div),a.targeting?(b.g=a.targeting,a.atf=a.targeting._a):
b.g={},a.atf&&("1"==a.atf?b.a="true":"0"==a.atf&&(b.a="false")),a.companion&&(b.c=a.companion),a.div&&(tmntag_removeByAttrValue(tmntag.a,"d",a.div),tmntag_removeByAttrValue(tmntagCache,"div",a.div)),a.sizeMapping&&(b.sm=a.sizeMapping),tmntag.a.push(b),tmntagCache.push(a),b}},tmntag.adunitTarget=function(a,b,c){"object"==l(a)?a.g[b]=c:"string"==typeof a&&(tmntag.localAdtargets=tmntag.localAdtargets||[],tmntag.localAdtargets[a]=tmntag.localAdtargets[a]||[],tmntag.localAdtargets[a].push([b,c]))},tmntag.target=
function(a){try{if("object"!=l(a)||a instanceof Array)return;for(var b in tmntag.g||(tmntag.g=a),a)if(a.hasOwnProperty(b)){var c=a[b];if(c&&tmntag_isArray(c)){for(var d=0;d<c.length;d++)c[d]=c[d]+"",c[d]=c[d].replace(/'|;|quot;|39;|&amp;|&|#|\r\n|\r|\n|\t|\f|\%0A|\"|\%22|\%5C|\%23|\%26|\%26|\%09/gm,""),c[d]=c[d].replace(/\%/gm,"");tmntag.g[b.replace(/'|&|#/g,"")]=c}else c&&(b=b.replace(/'|&|#/g,""),c+="",tmntag.g[b]=c.replace(/'|;|quot;|39;|&amp;|&|#|\r\n|\r|\n|\t|\f|\%0A|\"|\%22|\%5C|\%23|\%26|\%26|\%09/gm,
""),tmntag.g[b]=tmntag.g[b].replace(/\%/gm,""))}}catch(e){return console&&console.error&&console.error(e)}},tmntag.location=function(a){tmntag.l=encodeURIComponent(a),tmntag.su=1},tmntag.adTag=function(a,b){try{if(tmntag.disabledAdunits.find(function(b){return b===a}))return;var c=tmntag_getAdunitFromCache(a);if(!c||null===c)return void(void 0!==b&&!b||document.getElementById(a)?void 0===b?tmntag_callbacks.pushCallback(tmntag.adTag,[a]):tmntag_callbacks.pushCallback(tmntag.adTag,[a,b]):(tmntag_callbacks.pushCallback(tmntag.adTag,
[a,!1]),void 0===b&&document.write('<div id="'+a+'"></div>')));var d=void 0!==c.adunitRule&&"function"==typeof c.adunitRule&&1==c.adunitRule(a);if(void 0===c.adunitRule||d){if(void 0!==b&&!b||document.getElementById(a)||document.write('<div id="'+a+'"></div>'),!c.sizes){var e=document.getElementById(a);e&&(e.style.height="0px")}tmntag_applyAdunitStyle(a),d?googletag.cmd.push(function(){if(document.getElementById(a)&&tmntag){if(tmntag.slots&&!tmntag.slots[a])1===c.refresh?(tmntag_defineSlot(a,{},!0),
c.refresh=0):tmntag_defineSlot(a);(new Date).getTime();googletag.display(a)}else tmntagDisplayed[a]=1}):googletag.cmd.push(function(){if(document.getElementById(a)&&tmntag&&tmntag.slots&&tmntag.slots[a]){(new Date).getTime();googletag.display(a)}else tmntagDisplayed[a]=1})}}catch(f){return console&&console.error&&console.error(f)}},tmntag.loadScript=function(a,b,c){var d=void 0!==c&&null!=c,e="function"==typeof b,f=document.createElement("script");f.async=!0,f.src=a;var k;a=document.getElementsByTagName("script")[0];
d?k=setTimeout(function(){clearTimeout(k),e&&b()},c):e&&(f.onload=b),a.parentNode.insertBefore(f,a)},window.tmntag_filterAdUnitsByIds=function(a,b,c,d){a=(a=a||[])instanceof Array?a:[a];var e=b=b.filter(function(a){return a.d});return!d&&c&&tmntag.disableDFPRefresh&&(e=b.filter(function(b){return-1!==a.indexOf(b.d)}).filter(function(a){return tmntag.markupsInfo[a.d]&&tmntag.markupsInfo[a.d].rtbSold})),0===a.length?e:e.filter(function(b){return-1<a.indexOf(b.d)})},window.tmntag_getFacebookId=function(){var a=
tmntag.cookies.get("up_28");if(void 0!==a)return a},window.tmntag_getDigitrustId=function(){var a=tmntag.cookies.get("DigiTrust.v1.identity");if(void 0!==a){a=JSON.parse(atob(decodeURIComponent(a)));return encodeURIComponent(btoa(JSON.stringify({id:a.id,keyv:a.keyv})))}},tmntag.addCookies=function(){var a={},b=tmntag_getFacebookId();void 0!==b&&(a.up_28=b);b=tmntag.cookies.get("D_TOKEN");return void 0!==b&&(a.D_TOKEN=b),a},tmntag.getParams=function(){return""===window.location.search?{}:window.location.search.substr(1).split("&").reduce(function(a,
b){var c=b.indexOf("=");return a[b.substr(0,c)]=b.substr(c+1),a},{})},tmntag.setPersonalizedAdsMode=function(a){this.mode=a},tmntag.getPersonalizedAdsMode=function(){return this.mode||"allowed"},window.tmntag_formateMacromapList=function(a){return a&&0!==a.indexOf("$")?a.split("|"):[]},u=tmntag_formateMacromapList("fredzone.org|homecinema-fr.com|lemondenumerique.com|tomshw.it"),G=tmntag_formateMacromapList("buzzarena.com|clubic.com|dailygeekshow.com|driverscloud.com|frandroid.com|frawin.com|futura-sciences.com|gamergen.com|generation-nt.com|hitek.fr|iaddict.com|iphoneaddict.fr|kulturegeek.fr|legeekcestchic.eu|monwindows.com|nexxdrive.fr|numerama.com|phonandroid.com|tablette-tactile.net|tomsguide.fr|tomshardware.co.uk|tomshardware.fr|zebulon.fr"),H=tmntag_formateMacromapList("anandtech.com|coinranking.com|dailydot.com|dignifyed.com|gamepressure.com|idownloadblog.com|laptopmag.com|livescience.com|newsarama.com|sciencealert.com|shopsavvy.com|space.com|tomsguide.com|tomshardware.com|tomsitpro.com|toptenreviews.com|xda-developers.com|creativebloq.com|realite-virtuelle.com|objetconnecte.net|howtogeek.com|androidcentral.com|crackberry.com|imore.com|modmy.com|windowscentral.com"),
tmntag.setPersonalizedAdsMode("allowed"),tmntag_currentDomainIsInList(u)?tmntag.setPersonalizedAdsMode("blocked"):tmntag_currentDomainIsInList(G)?tmntag.setPersonalizedAdsMode("managed"):window.gdprUser&&(tmntag_currentDomainIsInList(H)?tmntag.setPersonalizedAdsMode("managed"):tmntag.setPersonalizedAdsMode("blocked")),window.tmntag_serializeState=function(a,b,c,d){c={};c.f=a?1:"",c.p=a?"":tmntag.p,c.s=tmntag.s,c.g=tmntag.g,c.l=tmntag.l,c.tt=tmntag.tt,c.tt=c.tt.replace(/'|;|quot;|39;|&amp;|&|#|\r\n|\r|\n|\t|\f|\%0A|\"|\%22|\%5C|\%23|\%26|\%26|\%09/gm,
""),c.fs=tmntag.fs,c.a=tmntag_filterAdUnitsByIds(b,tmntag.a||[],a,d),c.t=tmntag_timestamp(),c.ck=tmntag.addCookies(),c.tz=Math.round((new Date).getTimezoneOffset()),c.r=tmntag_clientDim(),c.ex=tmntag_additionalExperiments(),c.dgt=tmntag_getDigitrustId(),c.rf=encodeURIComponent(tmntag_referrer().replace("%","")),c.pam=tmntag.getPersonalizedAdsMode();a=tmntag.getParams();b=decodeURIComponent(a.key);if(a.key&&-1!==atob(b).indexOf(",")){a=atob(b).split(",");c.g=c.g||{},c.g.kw=c.g.kw||[],"string"==typeof c.g.kw&&
(c.g.kw=[c.g.kw]),c.g.kw=c.g.kw.concat(a)}return JSON.stringify(c).replace(/'|&|#/g,"")},window.tmntag_refreshNoWait=function(a,b){var c=[];if(void 0!==a){if(a instanceof Array)for(var d in a)(e=tmntag.slots[a[d]])&&c.push(e);else(e=tmntag.slots[a])&&c.push(e);if(0<c.length){for(var e in c)if(c.hasOwnProperty(e)&&b){for(var f in c[e].clearTargeting(),b)b.hasOwnProperty(f)&&c[e].setTargeting(f,b[f]);tmntag_setExtraTargetingInSlot(e)}googletag.pubads().refresh(c)}return console&&console.info&&console.info("-RAMP- Regular refresh "+
a)}googletag.pubads().refresh()},tmntag.refresh=function(a,b,c){window.indexLoaded&&tmntag_retrieveBidsFromIndex(a),a&&(a=tmntag_isArray(a)?a:[a]).forEach(function(a){var b=tmntag_getAdunitFromCache(a),d=tmntag.adtargets[a]&&tmntag.adtargets[a].find(function(a){return"_trn"===a[0]});if(void 0===c||b.targeting._trn){if(void 0===c&&b&&b.targeting&&b.targeting._trn&&tmntag.adtargets[a]){d=tmntag.adtargets[a].indexOf(d);tmntag.adtargets[a].splice(d,1),delete b.targeting._trn}}else tmntag.adtargets[a]=
tmntag.adtargets[a]||[],tmntag.adtargets[a].push(["_trn",c]),b.targeting._trn=c});a=tmntag_filterAdUnitsByIds(a,tmntag.a||[],!0,!1);for(var d=[],e=0;e<a.length;e++)d.push(a[e].d);d.forEach(function(a){tmntag.markupsInfo&&tmntag.markupsInfo[a]&&(tmntag.markupsInfo[a]={})}),tmntag.start(!0,d,function(){tmntag_refreshNoWait(d,b),tmntag.events.dispatchEvent("refresh",{divIds:d,trn:c})})},tmntag.refreshPixels=function(){if(void 0!==tmntag.tmn_pixels)for(var a=0;a<tmntag.tmn_pixels.length;a++){var b=tmntag.tmn_pixels[a];
b.isRefreshable()&&b.execute()}},window.tmntag_redirect=function(a,b,c){if(!a)return!1;var d={cp:"__CP__",bdrid:"__BDRID__",crid:"__CRID__",ad:"__AD__",pd:"__PRODUCT_ID__",tid:"__TID__",pvid:"__PVID__"};a="object"===l(b)?a.href:b;c="object"===l(b)?b:c;b=Math.floor(11E3*Math.random());b=("https:"==document.location.protocol?"https://":"http://")+"ramp.purch.com/event.js?t=CL&id="+(top.window.requestid?top.window.requestid:0)+"&r="+b;{c=c;var e="";if(c&&d)for(var f in d)d.hasOwnProperty(f)&&c.hasOwnProperty(d[f])&&
(e+="pd"===f?"&"+f+"=|"+c[d[f]]+"|":"&"+f+"="+c[d[f]]);d=e}d=b+d;return tmntag_injectScript(d,!1),window.open(a,"_blank").focus(),!1},window.tmntag_triggerEvent=function(a,b){var c="";if(b)for(var d in b){""!=c&&(c+="&");var e=b[d]+"";-1==e.indexOf("$")&&(c+=d+"="+e)}c="t="+a+"&r="+Math.floor(11E3*Math.random())+"&abr="+(tmntag.instartlogicEnabled()?"1":"")+"&"+c,"CP"==a&&(b&&b.ts&&-1==b.ts.indexOf("$")&&(c=c+"&tm_alt="+(Date.now()-b.ts)),tmntag.timing&&tmntag.timing.startTag&&tmntag.timing.loadTag&&
(c=c+"&tm_tlt="+(tmntag.timing.startTag-tmntag.timing.loadTag)));a=document.createElement("script");a.src="//ads2.servebom.com/event.js?"+c;c=document.getElementsByTagName("script")[0];c.parentNode.insertBefore(a,c)},window.tmntag_disableAdunit=function(a){tmntag.disabledAdunits.push(a)},window.tmntag_enableAdunit=function(a){tmntag.disabledAdunits.splice(tmntag.disabledAdunits.indexOf(a),1)},tmntag.adunitNew=function(a,b){if(!tmntag.disabledAdunits.find(function(b){return b===a.div})){tmntag.adunit(a);
var c=a.div;tmntag_defineSlot(c);googletag.display(c),b&&tmntag.refresh(c)}},tmntag.multipleAdunitClone=function(a,b,c){if(!("JSON"in window))return!1;var d=[];if(a.forEach(function(a){var e=a.divId;a=a.cloneDivId;var k=tmntag_getAdunitWithPrefixFromCacheForClone(e,c);if(!k)return!1;for(var q=tmntag_isArray(a)?a:[a],m=[],h=0,x=0;x<q.length;x++){var p;a=q[x];try{p=JSON.parse(JSON.stringify(k))}catch(J){return!1}if(p.div=a,p.targeting=p.targeting||{},b)for(var t in b)b.hasOwnProperty(t)&&b[t]&&(p.targeting[t]=
b[t]);var B=(tmntag.adparams=tmntag.adparams||{},tmntag.adparams[a]=tmntag.adparams[e]),r;if(r=c&&c.disableIncrementAccountPosition);else{if(r=c&&!c.resetPosition||0<x){{r=p;var w=h++;if(r){var v=r.account;if(v)if((v=v.split("/"))&&0<v.length){var y=v.reverse()[0];if(0<y.indexOf("-")){if((y=y.split("-"))&&0<y.length)for(var g=0;g<y.length;g++){var l=y[g];if(0==l.indexOf("p")){l=l.substring(1);if(!isNaN(l)){l=1*l+(w+1);y[g]="p"+l}}}w=y.join("-");v[0]=w,r.account=v.reverse().join("/")}}}r=void 0}}r=
r}B=(B,r);if(r=c&&c.disableIncrementPosition||k.disableIncrementPosition);else{{r=void 0;w=p;v=w.targeting||{};for(r in v)v.hasOwnProperty(r)&&"_p"===r&&v[r]&&(w.targeting[r]=1*v[r]+1);r=void 0}}B,r,tmntag.adunit(p),k.adunitRule&&tmntag.getAdParameters(e)&&"true"===tmntag.getAdParameters(e).on_clone_execute_preadunitrender&&k.adunitRule.apply(this,[a]);B=tmntag_defineSlot(a,p.targeting);d.push(a),m.push(B)}tmntag.events.dispatchEvent("adunitCloned",{originalDivId:e,clonedDivIds:d})}),c&&c.disableRefreshRamp)googletag.cmd.push(function(){for(var a=
0;a<d.length;a++)googletag.display(d[a]);tmntag_initialLoadDisabledMode&&googletag.pubads().refresh(tmntag_googleSlots(d))});else{a=c&&c.pageUrl||"";tmntag.start(!0,d,function(){googletag.cmd.push(function(){for(var a=0;a<d.length;a++)googletag.display(d[a]);tmntag_initialLoadDisabledMode&&googletag.pubads().refresh(tmntag_googleSlots(d))})},null,null,null,!0,a)}},tmntag.adunitClone=function(a,b,c,d){return tmntag.multipleAdunitClone([{divId:a,cloneDivId:b}],c,d)},tmntag.disableSingleRequest=function(){tmntag.sr=
!1},tmntag.disableCollapseEmptyDivs=function(){tmntag.ced=!1},tmntag.enableSingleRequest=function(){tmntag.sr=!0},tmntag.disableInitialLoad=function(){tmntag_initialLoadDisabled=!0,tmntag_initialLoadDisabledMode=!0},tmntag.onInlineAdunitRendered=function(a){var b=a.divid,c=tmntag_getAdunitFromCache(b),d={};d.div=b,d.adunit=c,a.size?d.size={width:a.size[0],height:a.size[1]}:d.size={width:0,height:0},d.isEmpty=!1,d.dfpCreativeId="",d.dfpLineItemId="",d.dfpCampaignId="",c.dfpCreativeId="",c.dfpLineItemId=
"",c.dfpCampaignId="",d._orig=a,tmntag_registerMouseOver(b),"undefined"!=typeof tmntag_adlabel&&tmntag_adlabel&&tmntag_adlabel.render(b,d),tmntag.onAdunitRenderedCallbackFunction(d),c&&c.onAdunitRendered&&"function"==typeof c.onAdunitRendered&&c.onAdunitRendered(a),tmntag.anchor(b),tmntag_updateAdUnitTiming(b)},window.tmntag_arrayToObject=function(a,b,c){return c=c||{},a.reduce(function(a,c){return-1!==b.indexOf(c[0])&&(a[c[0]]=c[1]),a},c)},tmntag.onAdunitRenderedPrivate=function(a){var b=a.slot.getSlotId().getDomId(),
c=tmntag_getAdunitFromCache(b),d={};if(d.div=b,d.adunit=c,a.size&&1<a.size[0]&&1<a.size[1]?d.size={width:a.size[0],height:a.size[1]}:tmntag.markupsInfo&&tmntag.markupsInfo[b]?d.size={width:tmntag.markupsInfo[b].width,height:tmntag.markupsInfo[b].height}:d.size={width:0,height:0},d.isEmpty=a.isEmpty,d.dfpCreativeId=a.creativeId||a.sourceAgnosticCreativeId,d.dfpLineItemId=a.lineItemId||a.sourceAgnosticLineItemId,d.dfpCampaignId=a.campaignId,c&&(c.dfpCreativeId=a.creativeId||a.sourceAgnosticCreativeId,
c.dfpLineItemId=a.lineItemId||a.sourceAgnosticLineItemId,c.dfpCampaignId=a.campaignId),d._orig=a,tmntag_registerMouseOver(b),"undefined"!=typeof tmntag_adlabel&&tmntag_adlabel&&tmntag_adlabel.render(b,d),tmntag_updateAdUnitTiming(b),tmntag.adunitServedEvent&&1<d.size.width&&1<d.size.height){var e={};tmntag.markupsInfo&&tmntag.markupsInfo[b]&&(e.bidderid=tmntag.markupsInfo[b].bidderid,e.adomain=tmntag.markupsInfo[b].adomain),tmntag.adtargets&&tmntag.adtargets[b]&&(e=tmntag_arrayToObject(tmntag.adtargets[b],
["_cp","_pl","_pdid","_wb"],e)),tmntag.pubtargets&&(e=tmntag_arrayToObject(tmntag.pubtargets,["_ex","_rid"],e));var f=e._pdid||"",k=e.adomain||"",q=e._cp||"",m=e._pl||"",h=e.bidderid||"3003",x=tmntag_getAdUnitTiming(b);tmntag_triggerEvent("AS",{id:e._rid,pdid:f,bid:e._wb,cp:q,pl:m,bdrid:h,ad:encodeURIComponent(k),e:e._ex,l:encodeURIComponent(tmntag_topLocation()),z:d.size.width+"x"+d.size.height,crid:encodeURIComponent(b),tm_alt:x.adLoadTime,tm_tlt:Math.max(0,x.tagLoadTime)})}tmntag.onAdunitRenderedCallbackFunction(d),
c&&c.onAdunitRendered&&"function"==typeof c.onAdunitRendered&&c.onAdunitRendered(a),tmntag.anchor(b),c&&tmntag_autorefresh(b)},tmntag.onAdunitViewablePrivate=function(a){a=a.slot.getSlotId().getDomId();tmntag_getAdunitFromCache(a).viewable=!0},tmntag.onAdunitRendered=function(a){a="function"==typeof a?a:function(){},this.callbacks=this.callbacks||[],this.callbacks.push(a),tmntag.onAdunitRenderedCallbackFunction=function(){var a=arguments;this.callbacks.forEach(function(b){b.apply(null,a)})}.bind(this)},
window.tmntag_xhrGet=function(a,b,c){var d=new XMLHttpRequest;d.withCredentials=!0,c&&(d.timeout=c),d.open("GET",a,!0),d.onreadystatechange=function(){this.readyState===XMLHttpRequest.DONE&&b(this.responseText)},d.send(null)},window.tmntag_executingStart=!1,window.tmntag_stackedPrefetchedAds=[],tmntag.start=function(a,b,c,d,e,f,k,q){function m(a,b){eval("try { "+a+" } catch (e) { console.error(e); }")}function h(a,b,c){tmntag_xhrGet(a,function(a){m(a),b()},c)}function x(a,b){tmntag_xhrGet(a,function(a){tmntag_stackedPrefetchedAds.push({callback:function(){m(a),
b()},created_at:new Date})})}function p(){return!!tmntag.pubtargets.find(function(a){return"prefetch"===a[0]&&"true"===a[1]})}function t(a,b){return a+"tmntag.js?"+Object.keys(b).map(function(a){return a+"="+b[a]}).join("&")}function B(a,b,c,d,e,f){var w=Object.keys(tmntag.adparams).filter(function(a){return tmntag.adparams[a].refresh&&"true"===tmntag.adparams[a].refresh}),r=tmntag_filterAdUnitsByIds(w,tmntag.a||[],!0,!1).map(function(a){return a.d});a.o=tmntag_serializeState(!0,r);w="${PAGE_DOMAIN:PREFETCH_DELAY_MS}";
w=isNaN(w)?0:w,window.setTimeout(function(){x(t(b,a),function(){"v"!==c&&(tmntag.f=1);var a=tmntag_filterAdUnitsByIds(d,tmntag.a||[],e,f);if(a)for(var b=0;b<a.length;b++){var w=tmntag_getAdunitFromCache(a[b].d);w&&(w.refresh=1)}tmntag_refreshNoWait(r,{})})},w)}q=q||"";var r=function(a,b,c,d,r,k){if(k&&tmntag.location(k),!tmntag_executingStart||a){a||(tmntag.enableSingleRequest(),googletag.cmd.push(function(){googletag.pubads().addEventListener("slotRenderEnded",function(a){tmntag.onAdunitRenderedPrivate(a)}),
googletag.pubads().addEventListener("impressionViewable",function(a){tmntag.onAdunitViewablePrivate(a)})})),tmntag_executingStart=!0;var w=Math.floor(11E3*Math.random()),m=tmntag_findURL();k=[];if("undefined"!=typeof amznads&&null!=amznads&&"function"==typeof amznads.getTokens){var v=amznads.getTokens();if(null!=v&&0<v.length)n=(n=v.join()).replace("kindle_pur_3x6","a3x6p100"),k.push({br:6,bs:n})}if("object"===("undefined"==typeof prebidSlots?"undefined":l(prebidSlots))&&null!=prebidSlots)for(var q in prebidSlots)if(prebidSlots.hasOwnProperty(q)){n=
prebidSlots[q];v=[];for(u in n){var y=n[u];"object"===l(y)&&v.push("a"+y.width+"x"+y.height+"p"+y.cpm+":"+y.ad)}0<v.length&&k.push({br:q,bs:v.join()})}var g={};g.v=e||TMNTAG_VERSION,g.r=w,g.o=tmntag_serializeState(a,b,f,r),a&&"v"!==f&&(tmntag.f=1);var n=tmntag_filterAdUnitsByIds(b,tmntag.a||[],a,r);if(a&&n)for(var u=0;u<n.length;u++)(q=tmntag_getAdunitFromCache(n[u].d))&&(q.refresh=1);g.uuid=defuuid,disableRTBBidding&&(g["ramp-rtb-disabled"]=1),"undefined"!=typeof Purch&&Purch.calypso&&Purch.calypso.pvid&&
(g.pvid=Purch.calypso.pvid),0<k.length&&(g.j=JSON.stringify(k)),g.at=f||"bnj",tmntag.instartlogicEnabled()&&(g.abr=1);var E=t(m,g);if(a)if(0<tmntag_stackedPrefetchedAds.length){u="${PAGE_DOMAIN:PREFETCHED_ADS_MAX_AGE}";u=isNaN(u)?30:u;k=tmntag_stackedPrefetchedAds.shift();(new Date).getTime()-k.created_at.getTime()>1E3*u?h(E,c,d):k.callback(),x(E,c)}else h(E,c,d);else tmntag.cmd.push(function(){tmntag.loadScript(E,function(){p()&&B(g,m,f,b,a,r)})});tmntag.timing.loadTag=(new Date).getTime()}};a&&
(window.amznads=null),"undefined"!=typeof amznads&&amznads&&amznads.asyncParams?setTimeout(function(){r(a,b,c,d,k,q)},PREBID_TIMEOUT):(PREBID_TIMEOUT=0,r(a,b,c,d,k,q))},window.tmntag_findURL=function(){for(var a=0;a<document.scripts.length;a++){var b=document.scripts[a],c=b.src.indexOf("tmnhead.js");if(0<c)return b.src.substring(0,c)}return"http://ads.servebom.com/"},window.tmntag_passback=function(a,b){if(b){var c=b.split("|");if(1==c.length)tmntag_render(a,b);if(4<=c.length)tmntag_render(a,c[0])||
a.write('<script type="text/javascript">google_ad_client = "ca-pub-5787592483766760";\ngoogle_ad_slot = "'+c[3]+'";\ngoogle_ad_width = '+c[1]+";\ngoogle_ad_height = "+c[2]+';\x3c/script><script type="text/javascript" src="//pagead2.googlesyndication.com/pagead/show_ads.js">\x3c/script>')}},window.tmntag_applyAdunitStyle=function(a){var b=tmntag.getAdParameters(a);if(b)if(b=b.adunit_style){a=document.getElementById(a);for(var b=b.trim().split(";"),c=0;c<b.length;c++)if(""!==b[c]){style=b[c].split(":");
var d=null;style[1]&&(0<=style[1].indexOf("!important")&&(style[1]=style[1].replace("!important",""),d="important"),a.style.setProperty(style[0].trim(),style[1].trim(),d))}}},tmntag.video.logError=function(a){if(tmntag.video.triggerErrorEventEnabled){var b={};tmntag.pubtargets&&(b=tmntag_arrayToObject(tmntag.pubtargets,["_rid"],b)),tmntag_triggerEvent("VE",{crid:a.code,ad:encodeURIComponent(a.tag),id:b._rid})}console.log("-RAMP VIDEO- Error",a)},window.tmntag_triggerVideoEvent=function(a,b,c){b={};
tmntag.markupsInfo&&tmntag.markupsInfo[c]&&(b.bidderid=tmntag.markupsInfo[c].bidderid,b.adomain=tmntag.markupsInfo[c].adomain),tmntag.vadtargets&&tmntag.vadtargets[c]&&(b=tmntag_arrayToObject(tmntag.vadtargets[c],["_cp","_pl","_pdid","_wb","_puids"],b)),tmntag.pubtargets&&(b=tmntag_arrayToObject(tmntag.pubtargets,["_ex","_rid"],b));c=b.bidderid||"3003";var d=b._pdid||"",e=b._puids||"",f=b.adomain||"",k=b._wb||"",q=b._cp||"",m=b._pl||"";tmntag_triggerEvent(a,{id:b._rid,pdid:d,puids:e,bid:k,cp:q,pl:m,
z:"540x304",bdrid:c,ad:encodeURIComponent(f),e:b._ex,l:encodeURIComponent(tmntag_topLocation())})},tmntag.video._videoView=function(a,b){tmntag_triggerVideoEvent("VV",a,b),console.log("-RAMP VIDEO- Video View",a)},tmntag.video._videoServed=function(a,b){tmntag_triggerVideoEvent("VS",a,b),console.log("-RAMP VIDEO- Video Served",a)},window.TimeoutPromise=function(a,b){return Promise.race([new Promise(a),new Promise(function(a){window.setTimeout(a,b)})])},window.tmntag_videoBeforePlayListItem=function(a,
b,c){if(console.log("-RAMP Video- tmntag_videoBeforePlayListItem"),void 0!==tmntag.video.disableAds&&tmntag.video.disableAds)console.log("-RAMP Video- Video Ads Disabled");else{var d=b.createInstream().init();(new TimeoutPromise(function(b){tmntag.vadtargets=[],tmntag.markupsInfo=tmntag.markupsInfo||{},tmntag.markupsInfo[a]=[],void 0===tmntag.video.status[a].fetch_count&&(tmntag.video.status[a].fetch_count=0);var d=tmntag_getAdunitFromCache(a);if(void 0===d||!d){d={div:c,sizes:[540,304]};void 0!==
tmntag.video.status[a].player_settings&&(d.targeting={apv:tmntag.video.status[a].player_settings.autostart?1:0}),tmntag.adunit(d)}tmntag.videoRefresh(c,function(){b()})},VIDEO_REFRESH_TIMEOUT)).then(function(){d.destroy();var a=tmntag.video.adTag(c,b.id);a?b.playAd(a):b.play()})}},tmntag.video.setup=function(a,b,c){a&&a.div&&a.account&&(tmntag.account(a.account),tmntag.adunit({div:a.div,sizes:[540,304]}),tmntag.video.start(a.div,b,c,a.div,!0))},tmntag.video.start=function(a,b,c,d,e){void 0!==b.advertising&&
b||(b.advertising={client:"googima"}),tmntag.instartlogicEnabled()&&(b.advertising.client="vast"),b.advertising.autoplayadsmuted=!0,b.advertising.vpaidcontrols=!0,b.advertising.creativeTimeout=2E4,b.advertising.requestTimeout=2E4,b.advertising.loadVideoTimeout=2E4,b.advertising.adsRequestTimeout=2E4,b.advertising.maxRedirects=6,void 0!==d&&d||(d=a),e&&c.setup(b),tmntag.video.status[a]={},tmntag.video.status[a].errors=[],tmntag.video.status[a].impressions=[],tmntag.video.status[a].player_settings=
b,(tmntag.video.status[a].player=c).on("adError",function(b){tmntag.video.logError(b),tmntag.video.status[a].errors.push(b)}),c.on("adImpression",function(b){tmntag.video._videoServed(b,d),tmntag.video.status[a].impressions.push(b)}),c.on("playlistItem",function(){c.once("beforePlay",function(){tmntag.video._videoView(event,d),tmntag_videoBeforePlayListItem(a,c,d)})})},tmntag.video.autostarted=function(a,b){tmntag.video.status[a]&&tmntag.video.status[a].player_settings&&(tmntag.video.status[a].player_settings.autostart=
b)},tmntag.video.adTag=function(a,b){var c;return c=tmntag.instartlogicEnabled()?function(a,b){var c=tmntag.vadtargets;b=a=0;if(void 0!==c)for(var d in c)for(var e=c[d],m=0;void 0!==e&&m<e.length;m++){if("_vst"===e[m][0]){var h=e[m][1];1<(h=h.split("/")).length&&(a=h[h.length-2]+"/"+h[h.length-1])}"_vrg"===e[m][0]&&(b=e[m][1])}d="s3.amazonaws.com/purch-us-standard-adserver-prod";"or"===b?d="s3-us-west-2.amazonaws.com/purch-us-west-2-adserver-prod":"eu"===b&&(d="s3-eu-west-1.amazonaws.com/purch-eu-west-1-adserver-prod");
b=Math.floor(11E3*Math.random());c="";return a&&(c="https://"+d+"/vast/"+a+"?cb="+b),c}():function(a,b){var c,d="",e=tmntag_getAdunitFromCache(a);if(e&&e.account)d=e.account;else{var m=tmntag_getAdUnit(a);m&&m.s?d=m.s:void 0!==tmntag.s&&tmntag.s&&(d=tmntag.s)}c=tmntag.l&&1==tmntag.su?tmntag.l.replace("%",""):encodeURIComponent(tmntag_topLocation().replace("%",""));var m=tmntag.vadtargets,h=tmntag.pubtargets;a=tmntag.adtargets[a];var d=["sz="+(tmntag.isMobile()?"480x270":"640x480"),"iu="+d,"ciu_szs=728x90,300x250",
"impl=s","gdfp_req=1","env=vp","output=xml_vast3","unviewed_position_start=1","url="+c,"correlator=__timestamp__"],g=["plID="+b,"ttID=__item-mediaid__","vdbl=yes","vvid_title=__item-title__","pos=preroll","max_ad_duration=30000"];e.targeting&&Object.keys(e.targeting).forEach(function(a){g.push(a+("="+e.targeting[a]))});b=!1;if(void 0!==h)for(var p in h)g.push(h[p][0]+"="+h[p][1]);if(void 0!==a)for(p in a)g.push(a[p][0]+"="+a[p][1]);if(void 0!==m)for(p in m){h=m[p];for(a=0;void 0!==h&&a<h.length;a++){if("_vst"===
h[a][0]){b=h[a][1];if(1<(b=b.split("/")).length){b=b[b.length-2]+"/"+b[b.length-1];g.push("_vst="+b)}}else g.push(h[a][0]+"="+h[a][1]);b=!0}if(b)break}return"https://pubads.g.doubleclick.net/gampad/ads?"+d.join("&")+"&cust_params="+encodeURIComponent(g.join("&"))}(a,b),console.log("-RAMP VIDEO- Video Tag: "+c),c},tmntag.videoRefresh=function(a,b){console.log("-RAMP VIDEO- Refresh");var c=function(){};"function"==typeof b&&(c=b),tmntag.start(!0,a,c,null,TMNTAGVIDEOREFRESH_VERSION,"v")},tmntag.processAdResponse=
function(a){tmntag_initialLoadDisabled&&(tmntag_initialLoadDisabled=!1,googletag.cmd.push(function(){tmntag_refreshNoWait(a)}))},window.tmntag_render=function(a,b){var c=!1;if(void 0!==tmntag.markups){var d=tmntag.markups[b];if(void 0!==d&&null!=d)if(d=(d=d.replace("a3x6p100","kindle_pur_3x6")).replace(/'\r\n|\r|\n/gm,""),tmntag_checkIfLazyLoaded(b)){var e=tmntag_debounce(function(){tmntag_inview(b)&&(document.removeEventListener("scroll",e),tmntag_writeToDocument(a,b,d))},50);document.addEventListener("scroll",
e),e()}else tmntag_writeToDocument(a,b,d),c=!0}return c},window.tmntag_checkIfLazyLoaded=function(a){var b=!1;return void 0!==tmntag.adtargets&&void 0!==tmntag.adtargets[a]&&tmntag.adtargets[a].forEach(function(a){b=b||"_ll"===a[0]&&a[1]}),b},window.tmntag_writeToDocument=function(a,b,c){var d=tmntag.markupsInfo[b].width,e=tmntag.markupsInfo[b].height;if("function"==typeof confiantWrapWithCallback&&CONFIANT_WRAPPER_ID){var f="purch_"+tmntag.markupsInfo[b].biddername;c={ad:c,bidder:f,size:d+"x"+e,
cpm:tmntag.adtargets[b]&&tmntag.adtargets[b].find(function(a){return"_cp"===a[0]})[1]};confiantWrapWithCallback(a,c,"clarium.global.ssl.fastly.net",CONFIANT_WRAPPER_ID,function(a,c,h,k,p,t){tmntag_triggerEvent("CB",{bdrid:tmntag.markupsInfo[b].bidderid||0,tid:f+":"+d+"x"+e,crid:c,ad:a,cp:t.prebid.cpm,id:window.requestid})})||(a.write(c.ad),a.close())}else a.write(c),a.close();(c=tmntag.slots[b])&&c.setTargeting("_bd","none");c=tmntag.markupsInfo[b];if(c&&(c.rtbSold=!0),a.defaultView&&a.defaultView.frameElement){c=
d+"px";var k=e+"px";a.defaultView.frameElement.width=c,a.defaultView.frameElement.height=k,tmntag_inIframe()&&self&&self.frameElement&&(self.frameElement.width=c,self.frameElement.height=k)}},window.tmntag_debounce=function(a,b,c){var d;return function(){var e=this,f=arguments,k=c&&!d;clearTimeout(d),d=setTimeout(function(){d=null,c||a.apply(e,f)},b),k&&a.apply(e,f)}},tmntag_ready(function(){if(tmntag)for(var a=0;a<tmntag.a.length;a++)tmntag_inlineMarkup(tmntag.a[a].d)}),tmntag.multipleInContentSelectors=
tmntag.multipleInContentSelectors||{},tmntag.multipleInContentParams=tmntag.multipleInContentParams||{},tmntag.multipleInContent=function(a,b){b=b||{};var c=tmntag.multipleInContentSelectors[a];!c&&b.selector&&(c=b.selector),b.clone=!0,Object.assign(b,tmntag.multipleInContentParams&&tmntag.multipleInContentParams[a]||{}),c&&MultipleIncontent(a,c,b)},window.MultipleIncontent=function(a,b,c){function d(a,b,c){a.parentNode&&a.parentNode.removeChild(a),b.insertAdjacentHTML(c,a.outerHTML),tmntag_applyAdunitStyle(a.id)}
(c=c||{}).position=c.position||"afterend";var e=c[tmntag.isMobile()?"repetitionMob":"repetitionDesk"];if(tmntag.multipleInContentSelectors[a]=b,tmntag.multipleInContentParams=tmntag.multipleInContentParams||{},tmntag.multipleInContentParams[a]=c,!a||!b)return!1;var f=[];b=function(a,b){var c=[];try{c=Array.prototype.slice.call(document.querySelectorAll(a))}catch(v){}if(!b.elementsFormula)return c;a=function(a){var b=a.match(/^(-?\d*)n(\s*(?:\+|-)\s*\d+)?$/);if(!b)return!1;a=b[1]||"1";a=isNaN(a)?"-1":
a;b=b[2]||"0";return b=b.replace(/\s/g,""),[Number(a),Number(b)]}(b.elementsFormula);if(!a)return[];var d=a[0],e=a[1];return c.filter(function(a,b){return 0<=(++b-e)/d&&(b-e)/d%1==0})}(b,c);if(b.length){for(var k=0,g=0,m=b.length;g<m;g++)if(b[g].classList.remove("ramp-incontent-progressive"),!b[g].classList.contains("ramp-incontent"))if(k++,!c.progressive||k<=c.progressive){if(b[g].classList.add("ramp-incontent"),!e||k<=e){if(0==g){var h=document.getElementById(a)||document.createElement("div");h.id=
a,d(h,b[g],c.position)}else{var h=a+"-"+g+(new Date).getTime(),x=document.createElement("div");x.id=h,x.classList.add("purchrtb-dynamic"),d(x,b[g],c.position),f.push(h)}k===c.progressive-1&&b[g].classList.add("ramp-incontent-progressive")}}else b[g].classList.add("ramp-incontent-progressive");c.clone&&tmntag.adunitClone(a,f,null,{disableRefreshRamp:0,resetPosition:1})}return tmntag_bindMultipleInContentInfiniteScroll(a),0<b.length},window.tmntag_bindMultipleInContentInfiniteScroll=(I=function(a){tmntag.inView(".ramp-incontent-progressive").on("enter",
function(b){b.classList.contains("ramp-incontent-progressive")&&tmntag.multipleInContent(a)})},F=!1,function(){if(!F)var a=I.apply(this,arguments);return F=!0,a}),window.tmntag_cloneDynamicZonesRan=!1,window.tmntag_onAdTagReady=function(){tmntag_cloneDynamicZonesRan||tmntag_cloneDynamicZones(!1)},window.tmntag_cloneDynamicZones=function(a){tmntag_cloneDynamicZonesRan=1;for(var b=document.querySelectorAll(".purchrtb-dynamic"),c={},d=0,e=b.length;d<e;d++){var f=b[d].id.lastIndexOf("-");if(0<f){f=b[d].id.substring(0,
f);c[f]||(c[f]=[]),c[f].push(b[d].id)}b[d].className=b[d].className.replace("purchrtb-dynamic","")}for(var k in c)tmntag.adunitClone(k,c[k],null,{disableRefreshRamp:a})},tmntag.cmd.executeCommands=function(){for(var a;a=tmntag.cmd.shift();)"function"==typeof a&&a()},tmntag.cmd.push=function(a){tmntag.cmd.executeCommands(),"function"==typeof a&&a()},tmntag.cmd.pushDefined=!0,window.tmntag_checkCommands=function(){tmntag.cmd.pushDefined?tmntag.cmd.executeCommands():setTimeout(tmntag_checkCommands,100)},
tmntag_checkCommands(),tmntag.apiReady=!0,tmntag.timing.endHead=(new Date).getTime(),tmntag.timing.debug=function(a){var b={timing:{}};return a&&tmntag.timing&&(b.timing.ramp={},b.timing.ramp.head=tmntag.timing.endHead-tmntag.timing.start,b.timing.ramp.loadTag=tmntag.timing.loadTag-tmntag.timing.start,b.timing.ramp.startTag=tmntag.timing.startTag-tmntag.timing.loadTag,b.timing.ramp.googleEnableServices=tmntag.timing.endEnableServices-tmntag.timing.startEnableServices,b.timing.ramp.endTag=tmntag.timing.endTag-
tmntag.timing.startTag,b.timing.ramp.total=tmntag.timing.endTag-tmntag.timing.start),window.performance&&(b.timing.ttfb=window.performance.timing.responseStart-window.performance.timing.requestStart,b.timing.ttlb=window.performance.timing.responseEnd-window.performance.timing.responseStart,b.timing.ttsr=window.performance.timing.domInteractive-window.performance.timing.responseEnd),b},tmntag.debug=function(){var a={};if(a.TMNAPI_VERSION=TMNAPI_VERSION,a.PREBID_TIMEOUT=PREBID_TIMEOUT,a.TMNTAG_VERSION=
TMNTAG_VERSION,a.timing=tmntag.timing.debug(),a.googletag="undefined"!=typeof googletag?googletag:"none",a.initialLoadEnabled=tmntag_initialLoadDisabled,a.singleRequestEnabled=tmntag.sr,a.collapseEmptyDivs=tmntag.ced,a.tmntag=tmntag,a.tmntagCache=tmntagCache,a.tmntagDisplayed=tmntagDisplayed,a.adunits=tmntag.a,a.googleSlots=tmntag.slots,a.pageLoation=tmntag_topLocation(),a.now=tmntag.t,a.timeZone=tmntag.tz,a.browserDim=tmntag.r,a.adParameters=tmntag.adparams,a.placement=tmntag.p,a.amazonAds="undefined"!=
typeof amznads?amznads:"none",a.prebidSlots="undefined"!=typeof prebidSlots?prebidSlots:"none",a.prebidAds="undefined"!=typeof prebidAds?prebidAds:"none",a.target=void 0!==tmntag.pubtargets?tmntag.pubtargets:"none",a.adunitTarget=void 0!==tmntag.adtargets?tmntag.adtargets:"none",a.adMarkups=void 0!==tmntag.markups?tmntag.markups:"none",googletag){var b=googletag.pubads().getSlots().map(function(a){a=a.getSlotElementId();var b=document.getElementById(a);return ret=b?{Message:"Checked",DIV:a,Type:"GOOD"}:
{Message:"Ad Slot declared in GPT, but NO DIV found on page",DIV:a,Type:"BAD !"},ret});console.table&&console.table(b),a.tagchecks=b}return a},window.PurchInContent=function(a){var b,c=function(a){return a.clone().find("script").remove().end().text().trim().length};return this.isvisible=function(a){return 1350<=c($("#news-content > p"))&&0===$("#news-content .shopping_generic, #news-content .responsiveTable, #news-content .responsiveTableCompact, #news-content .shopping_cpu, #news-content .shopping_gpu, #news-content shopping_ssd").length||
0<$(".inContentAd").length},this.createZone=function(a){if(0<$(".inContentAd").length)return MultipleIncontent(a,".inContentAd");var b=$("body").hasClass("mobile")?500:1E3;$("#news-content > p").each(function(d){var e=c($("#news-content > p:eq("+d+")"));if(c($("#news-content > p:lt("+d+")"))+e>=b&&350<=c($("#news-content > p:gt("+d+")")))return $("#news-content > p:eq("+d+")").after($("<div id="+a+' class="zonepub zonepub17"></div>')),!1})},(b=this.isvisible(a))&&this.createZone(a),b},tmntag.isMobile=
function(){var a,b=!1;return a=navigator.userAgent||navigator.vendor||window.opera,(/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|mobile.+firefox|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows ce|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4)))&&(b=!0),b},window.tmntag_iabVendorIdMapping={11:185,"23_25_26_29_33":32,22:69,9:104,24:13,14:28,5:76,19:52,36:24,45:76,32:202,17:81,2:10,44:277,42:335,46:76,27:236,57:25,55:184},window.tmntag_waitForCMP=function(a){return"function"!=typeof window.__cmp?window.setTimeout(function(){tmntag_waitForCMP(a)},100):a()},tmntag.executeWithGDPRConsent=function(a,b){switch(tmntag.getPersonalizedAdsMode()){case "blocked":return;case "allowed":return b();case "managed":var c=tmntag_formateMacromapList("phonandroid.com|frandroid.com|generation-nt.com|gamergen.com|numerama.com|driverscloud.com|hitek.fr|tomsguide.fr|tomshardware.fr|creativebloq.com|howtogeek.com|androidcentral.com|crackberry.com|imore.com|modmy.com|windowscentral.com");
if(tmntag_currentDomainIsInList(c))return b();tmntag_waitForCMP(function(){window.__cmp("addEventListener","cmpReady",function(){window.__cmp("getVendorConsents",[a],function(c){if(c.vendorConsents&&c.vendorConsents[a])return b()})})})}},window.userSyncPixels={},userSyncPixels._cookiesMap=tmntag.cookies.getAll(),userSyncPixels.create=function(a,b,c,d,e,f){e=e||"usp."+a,f=void 0===f||f,userSyncPixels._cookiesMap[e]||(tmntag.executeWithGDPRConsent(tmntag_iabVendorIdMapping[a],function(){var a=tmntag_formateMacromapList(b);
tmntag_currentDomainIsInList(a)===c&&d()}),f&&(tmntag.cookies.set(e,1,"604800"),userSyncPixels._cookiesMap[e]=1))},window.purch_history=function(a){a.pvLoggingDisabled=!0,a.pageHistory={},a.pageHistory[window.location.pathname]=1;!function(a){var b=a.replaceState;a.replaceState=function(c,d,g){return"function"==typeof a.onreplacestate&&window.location.pathname!=g&&a.onreplacestate(c,d,g),b.apply(a,arguments)};var d=a.pushState;a.pushState=function(b,c,g){return"function"==
typeof a.onpushstate&&window.location.pathname!=g&&a.onpushstate(b,c,g),d.apply(a,arguments)}}(window.history),history.onreplacestate=history.onpushstate=function(b,c,d){var e;a.onPageChangedDisabled||(e=d,a.pageHistory[e]||(a.pageHistory[e]=1,purch_history_onNewPage(e)))},window.purch_history_onNewPage=function(b){if(!a.pvLoggingDisabled){b={};a.pubtargets&&(b=tmntag_arrayToObject(a.pubtargets,["_ex","_rid"],b)),tmntag_triggerEvent("PV",{id:b._rid,e:b._ex,l:encodeURIComponent(tmntag_topLocation())})}}},
purch_history(tmntag),function(a,b){var c=tmntag_formateMacromapList("buzzarena.com|clubic.com|dailygeekshow.com|driverscloud.com|frandroid.com|frawin.com|futura-sciences.com|gamergen.com|generation-nt.com|hitek.fr|iaddict.com|iphoneaddict.fr|kulturegeek.fr|legeekcestchic.eu|monwindows.com|nexxdrive.fr|numerama.com|phonandroid.com|tablette-tactile.net|tomsguide.fr|tomshardware.co.uk|tomshardware.fr|zebulon.fr"),d=tmntag_formateMacromapList("anandtech.com|coinranking.com|dailydot.com|dignifyed.com|gamepressure.com|idownloadblog.com|laptopmag.com|livescience.com|newsarama.com|sciencealert.com|shopsavvy.com|space.com|tomsguide.com|tomshardware.com|tomsitpro.com|toptenreviews.com|xda-developers.com|creativebloq.com|realite-virtuelle.com|objetconnecte.net|howtogeek.com|androidcentral.com|crackberry.com|imore.com|modmy.com|windowscentral.com");if(tmntag_currentDomainIsInList(c)||a.gdprUser&&tmntag_currentDomainIsInList(d)){if(a.__cmp||(a.__cmp=function(){(a.attachEvent||a.addEventListener)("message",function(b){a.__cmp.receiveMessage(b)},!1),function p(){if(!a.frames.__cmpLocator)if(b.body){var c=b.createElement("iframe");
c.style.display="none",c.name="__cmpLocator",b.body.appendChild(c)}else setTimeout(p,5)}();var c=[],d=function(b,d,e){"ping"===b?e&&e({gdprAppliesGlobally:!!(a.__cmp&&a.__cmp.config&&a.__cmp.config.storeConsentGlobally),cmpLoaded:!1}):c.push({command:b,parameter:d,callback:e})};return d.commandQueue=c,d.receiveMessage=function(b){var c="string"==typeof b.data,d={};try{d=c?JSON.parse(b.data):b.data}catch(w){}if(d.__cmpCall){var e=d.__cmpCall;a.__cmp(e.command,e.parameter,function(a,d){a={__cmpReturn:{returnValue:a,
success:d,callId:e.callId}};b.source.postMessage(c?JSON.stringify(a):a,"*")})}},d}()),tmntag_currentDomainIsInList(tmntag.config.get("GDPR_PII_CMP_LOAD_BOOST_DOMAINS"))){var e=a.Purch=a.Purch||{};e.AdTech=e.AdTech||{},e.AdTech.cmpQueue=e.AdTech.cmpQueue||[],e.AdTech.showCMPModal=function(){__cmp("addEventListener","cmpReady",function(){__cmp("showConsentTool",1)})};e.AdTech.consentAll=function(){__cmp("addEventListener","cmpReady",function(){__cmp("consentAll")})},e.AdTech.onConsent=function(a){__cmp("addEventListener",
"onSubmit",a)},e.AdTech.onClose=function(a){__cmp("addEventListener","onClose",a)};var f=function(a){var c=b.createElement("iframe");c.src="https://ads.servebom.com/add_cookies?key=euconsent&value="+a,c.style.display="none",b.body.appendChild(c)},g=!1,q=function(a,b){if(!g){g=!0,b=b||{};a=(a||{}).vendorListVersion;var c=b.created,d=b.vendorListVersion;(!c||a&&d!==a)&&e.AdTech.showGDPRBanner?e.AdTech.showGDPRBanner():c&&f(b.metadata)}};if("PIITrackingWithConsent"===a.gdprMode||"managed"===tmntag.getPersonalizedAdsMode()){a.__cmp=
a.__cmp||{},a.__cmp.config={globalVendorListLocation:"https://purch.mgr.consensu.org/vendorlist.json",globalConsentLocation:"https://purch.mgr.consensu.org/portal.html",customPurposeListLocation:"https://purch.mgr.consensu.org/purposes.json",storePublisherData:!1,storeConsentGlobally:!0};c=b.createElement("script");c.async=!0,c.addEventListener("load",function(){__cmp("addEventListener","onSubmit",function(){__cmp("getConsentData",null,function(a){f(a.consentData)})}),__cmp("addEventListener","cmpReady",
function(){__cmp("getVendorList",null,function(b){var c=a.setTimeout(function(){q(b)},100);__cmp("getVendorConsents",null,function(d){a.clearTimeout(c),q(b,d)})}),function h(){if(0<e.AdTech.cmpQueue.length)for(;0<e.AdTech.cmpQueue.length;){var a=e.AdTech.cmpQueue.shift();if("function"==typeof a)a();else switch(a){case "consentAll":e.AdTech.consentAll()}}e.AdTech.cmpQueue.push=function(a){Array.prototype.push.call(e.AdTech.cmpQueue,a),h()}}()})}),c.src="https://purch.mgr.consensu.org/cmp.bundle.js",
b.body.appendChild(c)}}}else tmntag_currentDomainIsInList(tmntag.config.get("GDPR_MINISTUB_FOR_NON_EU_USERS_DOMAIN_LIST",[]))&&!a.__cmp&&(a.__cmp=function(b,c,d){"ping"===b?d&&d({gdprAppliesGlobally:!!(a.__cmp&&a.__cmp.config&&a.__cmp.config.storeConsentGlobally),cmpLoaded:!1}):"getConsentData"===b&&d&&d({gdprApplies:!1,hasGlobalConsent:null,hasGlobalScope:null,consentData:null})})}(window,document),tmntag.events=function(){function a(a){this.name=a,this.callbacks=[]}function b(){this.events={}}return a.prototype.registerCallback=
function(a){this.callbacks.push(a)},b.prototype.dispatchEvent=function(a,b){if("string"!=typeof a)throw new Error('"eventName" must be a string');this.events[a]&&this.events[a].callbacks.forEach(function(a){a(b)})},b.prototype.addEventListener=function(b,d){if("string"!=typeof b)throw new Error('"eventName" must be a string');if("function"!=typeof d)throw new Error('"callback" must be a function');this.events[b]=this.events[b]||new a(b),this.events[b].registerCallback(d)},b.prototype.removeEventListener=
function(a,b){if("string"!=typeof a)throw new Error('"eventName" must be a string');if("function"!=typeof b)throw new Error('"callback" must be a function');this.events[a]&&-1!==this.events[a].callbacks.indexOf(b)&&this.events[a].callbacks.splice(this.events[a].callbacks.indexOf(b),1)},new b}(),tmntag.inView=function(a){function b(a){this.elements=a,this.current=[],this.handlers={enter:[],exit:[]}}function c(b){var c=b.getBoundingClientRect();b=c.top;var d=c.right,e=c.bottom,f=c.left,g=.5*c.width,
c=.5*c.height;return c<e&&a.innerWidth-f>g&&a.innerHeight-b>c&&g<d}b.prototype.check=function(){return this.elements.forEach(function(a){var b=c(a),d=this.current.indexOf(a),e=-1<d,f=!b&&e;b&&!e&&(this.current.push(a),this.emit("enter",a)),f&&(this.current.splice(d,1),this.emit("exit",a))},this),this},b.prototype.on=function(a,b){return this.handlers[a].push(b),this},b.prototype.emit=function(a,b){for(var c=this.handlers[a].length;-1<--c;)this.handlers[a][c](b);return this};var d,e,f,g,q,m,h,l,p=
(d=function(){t.history.forEach(function(a){t[a].check()})},e=100,m=null,h=0,l=function(){h=new Date,m=null,q=d.apply(f,g),m||(f=g=null)},function(){var a=new Date,b=e-(a-h);return f=this,g=arguments,b<=0||e<b?(m&&(clearTimeout(m),m=null),h=a,q=d.apply(f,g),m||(f=g=null)):m||(m=setTimeout(l,b)),q});["scroll","resize","load"].forEach(function(b){a.addEventListener(b,p)}),a.MutationObserver&&a.addEventListener("DOMContentLoaded",function(){(new MutationObserver(p)).observe(document.body,{attributes:!0,
childList:!0,subtree:!0})});var t={history:[]},n=function(a){if("string"==typeof a){var c=[].slice.call(document.querySelectorAll(a));return-1<t.history.indexOf(a)?t[a].elements=c:(t[a]=new b(c),t.history.push(a)),t[a]}};return n.is=c,n}(window),window.tmntag_once=function(a){var b=!1;return function(){if(!b)var c=a.apply(this,arguments);return b=!0,c}},tmntag.autorefresh=function(a){function b(b,c){var d,e,f=c,g=!1;this.pause=function(){a.clearTimeout(d),f-=new Date-e,g=!0},this.resume=function(){e=
new Date,a.clearTimeout(d),d=a.setTimeout(b,f),g=!1},this.remaining=function(){return g?Math.max(0,f):Math.max(0,f-(new Date-e))},this.resume()}function c(a,c,d,e){var f,g,k=!1,p=!1,t=!1;return this.entersViewport=function(){if(k=!0,p)return this.executeCallback();g?g.resume():g=new b(function(){p=!0,this.executeCallback()}.bind(this),c)},this.leavesViewport=function(){k=!1,g.pause()},this.executeCallback=function(){t&&p&&k&&(h("["+d+"] adunit has spend "+(c/1E3+"s")+" in view and "+(a/1E3+"s")+" timer is finished and element is in view, we can try to refresh it"),
e())},this.stop=function(){f&&f.pause(),g&&g.pause()},this.remaining=function(){return[f.remaining(),g.remaining()]},f=new b(function(){t=!0,this.executeCallback()}.bind(this),a),this}function d(a){h("["+a.id+"] Reinitializing "+(e/1E3+"s")+" timer"),a.autorefreshTimers&&a.autorefreshTimers.stop(),a.autorefreshTimers=new c(e,f,a.id,function(){var b;{a:{b=a.id;var c=document.querySelector("#"+b),e=(c.refreshCount++,delete c.viewableTimer,delete c.canRefresh),f;{b:{f=b;if(l<c.refreshCount){f=(h("["+
f+"] Enough refreshes, this one was the last one"),!1);break b}if(q=f,!(tmntag.markupsInfo&&tmntag.markupsInfo[q]&&tmntag.markupsInfo[q].rtbSold)){var k=(p=tmntag_getAdunitFromCache(f))&&p.dfpCampaignId,p=(n=tmntag_getAdunitFromCache(f))&&n.dfpLineItemId;f=k?m[k]?-1===m[k].lineItems.indexOf(String(p))&&-1===m[k].lineItems.indexOf("*")?(h("["+f+"] Can't refresh, ad has not been served by RAMP, its DFP Order ID ("+k+") is in the DFP IDs whitelist, but its Line Item ID ("+p+") is not in the DFP IDs whitelist and this DFP Order doesn't allow any Line Item"),
!1):(h("["+f+"] Can refresh, ad has not been served by RAMP, but its DFP Order ID ("+k+") and its DFP Line Item ID ("+p+") are in the DFP IDs whitelist"),!0):(h("["+f+"] Can't refresh, ad has not been served by RAMP and its DFP Order ID ("+k+") is not in the DFP IDs whitelist"),!1):(h("["+f+"] Can't refresh, ad has not been served by RAMP and its DFP Order ID is null"),!1);break b}var n,p,q;n=(k=f,tmntag.markupsInfo&&tmntag.markupsInfo[k]&&tmntag.markupsInfo[k].bidderid);f=(h("["+f+"] Bidder ID: "+
(n||"null")),-1!==g.indexOf(n)||(h("["+f+"] Can't refresh, it's currently displaying an ad from bidder "+n),!1))}}if(e,!f){b=c.refreshable=!1;break a}h("["+b+"] Refreshing (refresh #"+c.refreshCount+")"),tmntag.refresh(b,void 0,String(c.refreshCount-1)),d(c);b=void 0}}!b}),tmntag.inView.is(a)&&tmntag.inView("#"+a.id).emit("enter",a)}var e,f,g,l,m,h=function(a){console.log("%cAutorefresh ["+(new Date).toLocaleTimeString()+"]%c "+a,"text-transform: uppercase; font-size: smaller; font-weight: bold; color: white; background-color: black; padding: .2em .5em; border-radius: 3px",
"")},n=tmntag_once(function(){tmntag.events.addEventListener("refresh",function(a){a&&a.divIds&&!a.trn&&a.divIds.forEach(function(a){a=document.getElementById(a);a.autorefreshTimers&&(a.autorefreshTimers.stop(),d(a))})})});return function(a,b){var c;e=(b=b||{}).refreshDelay||3E4,f=b.viewableDelay||1E4,l=b.limit||4,g=b.refreshableBiddersIds||[],c=b.refreshableDFPIds||[],m=c.map(function(a){return a.split(":")}).reduce(function(a,b){var c=0<b.length&&b[0];b=1<b.length&&b[1]||"*";return a[c]=a[c]||{lineItems:[]},
a[c].lineItems.push(b),a},{}),(h=b.debug?h:function(){})("Configuration:"),h("Refresh delay: "+(e/1E3+"s")),h("Viewable delay: "+(f/1E3+"s")),h("Refresh limit: "+l),h("Refreshable bidders: "+g.join(", ")),h("Refreshable DFP IDs: "+(b.refreshableDFPIds||[]).join(", ")),h("Adunits selected for autorefresh: "+a.join(", ")),a.forEach(function(a){var b="#"+a,c=document.querySelector(b);c&&(c.refreshCount=c.refreshCount||0,c.refreshable=!0,tmntag.inView(b).on("enter",function(b){b.autorefreshTimers.entersViewport(),
h("["+a+"] Adunit just entered viewport. "+(b.autorefreshTimers.remaining()[0]/1E3+"s")+" left in refresh timer. "+(b.autorefreshTimers.remaining()[1]/1E3+"s")+" left in viewability timer.")}).on("exit",function(b){b.autorefreshTimers.leavesViewport(),h("["+a+"] Adunit just left viewport. "+(b.autorefreshTimers.remaining()[0]/1E3+"s")+" left in refresh timer. "+(b.autorefreshTimers.remaining()[1]/1E3+"s")+" left in viewability timer.")}),d(c))}),n()}}(window),C=window,D=document,z=tmntag,z.anchor=
function(a){if("true"!==z.getAdParameters(a,"anchor"))return!1;var b=D.getElementById.bind(D),c=C.GUMGUM;c&&c.isad&&c.isad.closeAd();var d,e=b(a);if(d=a,z&&z.markupsInfo&&z.markupsInfo[d]&&"48"===z.markupsInfo[d].bidderid&&z.markupsInfo[d].rtbSold)return e&&(e.style.display="none"),!0;if(!e)return console.error("-- RAMP --- Element Not Found in DOM "+a),!1;e.classList.add("purch-anchor-adunit");var f,g,l,m,h,n=z.getAdParameters(a,"anchor.bottomOffset")||0;if(c=z.getAdParameters(a,"anchor_cookieBannerSelector")){var p=
D.querySelector(c);p&&(f=p.getBoundingClientRect().height,n+=f,(new MutationObserver(function(a){a.forEach(function(a){a=Array.prototype.slice.call(a.removedNodes);(-1<a.indexOf(p)||a.find(function(a){return a.contains(p)}))&&(e.style.bottom=n-f+"px")})})).observe(D.body,{subtree:!0,childList:!0}))}Object.assign(e.style,{position:"fixed",bottom:n+"px",zIndex:"1000",display:"block",width:"100%",left:0,textAlign:"center",backgroundColor:"rgba(255, 255, 255, .8)",boxShadow:"0 -1px 1px 0 rgba(0, 0, 0, .2)",
paddingTop:"5px"}),g=/iPad|iPhone|iPod/.test(navigator.userAgent)&&!C.MSStream,l=C.devicePixelRatio||1,m=C.screen.width*l,h=C.screen.height*l,g&&(1125===m&&2436===h||828===m&&1792===h||1242===m&&2688===h)&&n<15&&(e.style.bottom="15px");g="tmn-mobile-anchor-close-button-link-id_"+a;var t=b(g);return t||((t=D.createElement("a")).addEventListener("click",function(){b(a).style.display="none"}),t.innerHTML="&times;",t.id=g,Object.assign(t.style,{fontFamily:"sans-serif",color:"#b2b2b2",backgroundColor:"rgba(255, 255, 255, .5)",
textDecoration:"none",borderRadius:"50%",position:"absolute",right:"5px",textAlign:"center",display:"none",width:"20px",height:"20px",lineHeight:"20px",border:"1px solid #b2b2b2",top:"8px"})),e.appendChild(t),setTimeout(function(){t.style.display="inline-block"},3E3),!0},window.tmntag_processTmntagResponse=tmntag.processTmntagResponse=function(){if(TMNTAG_READY=1,void 0!==tmntag.pubtargets&&tmntag.pubtargets&&(window.experimentId&&tmntag.pubtargets.push(["_experiment",experimentId]),"undefined"!=
typeof tmntag_referrer)){var a=tmntag_referrer();0<a.indexOf("google")?tmntag.pubtargets.push(["_ts","gs"]):0<a.indexOf("yahoo")?tmntag.pubtargets.push(["_ts","ys"]):0<a.indexOf("bing")&&tmntag.pubtargets.push(["_ts","bs"])}tmntag.timing&&(tmntag.timing.startTag=(new Date).getTime()),"undefined"!=typeof googletag&&googletag.cmd.push(function(){if(window.tmntag&&tmntag.isNonPersonalizedAds&&googletag.pubads().setRequestNonPersonalizedAds(1),"function"==typeof tmntag_defineSlot&&"undefined"!=typeof tmntag&&
void 0!==tmntag.a)if(tmntag&&1==tmntag.f){if(tmntag.adtargets)for(var a in tmntag.adtargets)tmntag.adtargets.hasOwnProperty(a)&&tmntag_defineAdUnit(a)}else for(var c=0;c<tmntag.a.length;c++){a=tmntag.a[c].d;tmntag_defineAdUnit(a)}else tmntag_defineSlots();if("undefined"!=typeof tmntag&&void 0!==tmntag.pubtargets)for(c=0;c<tmntag.pubtargets.length;c++)googletag.pubads().setTargeting(tmntag.pubtargets[c][0],tmntag.pubtargets[c][1]);if("undefined"!=typeof tmntag&&void 0!==tmntag.su&&1===tmntag.su&&void 0!==
tmntag.l&&googletag.pubads().set("page_url",decodeURIComponent(tmntag.l)),1!==tmntag.f&&"undefined"!=typeof tmntag&&void 0!==tmntag.sr&&1==tmntag.sr&&googletag.pubads().enableSingleRequest(),1!==tmntag.f&&"undefined"!=typeof tmntag&&"undefined"!=typeof tmntag_il&&0==tmntag_il&&(console.log("- RAMP - DISABLE INITIAL LOAD"),googletag.pubads().disableInitialLoad()),1!==tmntag.f&&"undefined"!=typeof tmntag&&void 0!==tmntag.ced&&1==tmntag.ced&&googletag.pubads().collapseEmptyDivs(),1!==tmntag.f){for(divid in tmntag.timing&&
(tmntag.timing.startEnableServices=(new Date).getTime()),"function"===tmntag.instartlogicEnabled&&tmntag.instartlogicEnabled()||googletag.enableServices(),tmntag_setGptLoaded(),tmntag_callbacks.executeCallbacks(),tmntag.timing&&(tmntag.timing.endEnableServices=(new Date).getTime()),tmntag.slots)(a=document.getElementById(divid))&&void 0!==a&&tmntagDisplayed&&1==tmntagDisplayed[divid]&&googletag.display(divid);"undefined"==typeof tmntag||"undefined"==typeof tmntag_il||0!=tmntag_il||disable_refresh||
(console.log("- RAMP - REFRESH"),googletag.pubads().refresh())}"function"==typeof tmntag_onAdTagReady&&tmntag_onAdTagReady()}),tmntag.timing&&(tmntag.timing.endTag=(new Date).getTime())},window.indexLoaded&&(tmntag.processTmntagResponse=function(){var a=tmntag.config.get("TEST_RAMP_INDEX_DEFAULT_TIMEOUT_BEFORE_DFP",1300);if(window.performance&&window.performance.getEntriesByType){var b=performance.getEntriesByType("resource").find(function(a){return a.name.match(/tmntag/)});b&&(a=Math.max(tmntag.config.get("TEST_RAMP_INDEX_MAX_INDEX_TIMEOUT_BEFORE_DFP",
2E3)-Math.round(b.duration),0))}console.log("- RAMP - Waiting "+a+"ms before processing tmntag.js response [current time: "+(new Date).getTime()+"]"),window.setTimeout(function(){console.log("- RAMP - Processing tmntag.js response [current time: "+(new Date).getTime()+"]"),tmntag_processTmntagResponse()},a)})}}));
tmntag.floorprices={};
tmntag.headerbidderstodrop={};try {
tmntag_ready(function() {

userSyncPixels._fragment=document.createElement("div");

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

userSyncPixels.create(11,"buyerzone.com|businessnewsdaily.com",false,function(){var a=document.createElement("script");a.type="text/javascript";a.async=true;a.src="//bttrack.com/pixel/cookiesync?source=cfc80ad2-7c39-4243-92d6-3ecc1b9a38c6&secure=1";userSyncPixels._fragment.appendChild(a)});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

userSyncPixels.create("23_25_26_29_33","buyerzone.com|businessnewsdaily.com",false,function(){var c=Math.floor(Math.random()*11E3),a=document.createElement("img");a.style.display="none";var b=document.location.protocol==="https:"?"https":"http";a.src=b+"://ib.adnxs.com/getuid?"+b+":%2F%2Fpixel.servebom.com%2Fpartner%3Fcb%3D"+c+"%26svc%3Dus%26id%3D23%2C25%2C26%2C29%26uid%3D$UID";userSyncPixels._fragment.appendChild(a)});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

function requestToken(){var a=document.getElementById(frameId);a.contentWindow.postMessage("GET_FB_TOKEN_198782813737","https://www.facebook.com")}function receiveFBToken(a){if(a.origin.indexOf("https://www.facebook.com")!==-1){var b="; expires="+a.data.expAfter;a=JSON.parse(a.data);document.cookie="up_28="+encodeURIComponent(a.fbToken)+b+"; path=/"}}
if(!window.gdprUser&&document.location.host.indexOf("creativebloq.com")<=0){var frameId="fb_iframe";if(typeof window.INSTART==="undefined"){try{var fbIframe=document.createElement("iframe");fbIframe.id=frameId;fbIframe.width="0";fbIframe.height="0";fbIframe.frameBorder="0";fbIframe.src="https://www.facebook.com/audiencenetwork/token/v1/";document.body.appendChild(fbIframe);fbIframe.onload=function(){requestToken()}}catch(a){console.error(a)}window.addEventListener("message",receiveFBToken,false)}};

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

userSyncPixels.create("51_52_53_54","creativebloq.com|buyerzone.com|businessnewsdaily.com",false,function(){var a=document.createElement("span"),c=Math.floor(Math.random()*11E3);a.style.display="none";var d=document.location.protocol==="https:"?"https":"http",b=document.createElement("iframe");b.style.display="none";b.src="//sync.mathtag.com/sync/img?mt_exid=66&redir="+encodeURIComponent(d+"://pixel.servebom.com/partner?cb="+c+"&svc=us&id=51%2C52%2C53%2C54&uid=[MM_UUID]");a.appendChild(b);userSyncPixels._fragment.appendChild(a)});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

userSyncPixels.create("22","buyerzone.com|businessnewsdaily.com",false,function(){var a=document.createElement("span"),b=Math.floor(Math.random()*11E3);a.style.display="none";var c=document.location.protocol==="https:"?"https":"http";a.innerHTML='<iframe style="display:none" src="//us-u.openx.net/w/1.0/cm?id=de2d90e5-4d26-4c8c-a342-3edcde51fdb1&ph=25af9286-f23b-4b02-abcd-f2ee3b564dab&r='+c+"%3A%2F%2Fpixel.servebom.com%2Fpartner%3Fcd%3D"+b+'%26svc%3Dus%26id%3D22%26uid%3D"></iframe>';userSyncPixels._fragment.appendChild(a)});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

userSyncPixels.create(9,"buyerzone.com|businessnewsdaily.com",false,function(){if(window.gdprUser)return;try{var b=document.createElement("script");b.src="//sync.go.sonobi.com/uc.js";userSyncPixels._fragment.appendChild(b)}catch(a){console.error(a)}try{var e=Math.floor(Math.random()*11E3),c=document.createElement("img"),d=document.location.protocol==="https:"?"https":"http";c.src=d+"://purch-sync.go.sonobi.com/us?"+d+"://pixel.servebom.com/partner?cb="+e+"&svc=us&id=9&uid=[UID]";userSyncPixels._fragment.appendChild(c)}catch(a){console.error(a)}});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

userSyncPixels.create(24,"buyerzone.com|businessnewsdaily.com",false,function(){var a=document.createElement("iframe"),c=Math.floor(Math.random()*11E3);a.style.display="none";var b=document.location.protocol==="http:"?"http":"https";a.defer=true;a.src=b+"://ap.lijit.com/pixel?redir="+b+":%2F%2Fpixel.servebom.com%2Fpartner%3Fcb%3D"+c+"%26svc%3Dus%26id%3D24%26uid%3D$UID";userSyncPixels._fragment.appendChild(a)});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

userSyncPixels.create(14,"creativebloq.com|buyerzone.com|newegg.com|businessnewsdaily.com",false,function(){var a=document.createElement("span"),b=Math.floor(Math.random()*11E3);a.style.display="none";a.innerHTML='<iframe style="display:none" src="//eb2.3lift.com/getuid?redir=%2F%2Fpixel.servebom.com%2Fpartner%3Fcb%3D'+b+'%26svc%3Dus%26id%3D14%26uid%3D%24UID"></iframe>';userSyncPixels._fragment.appendChild(a)});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

userSyncPixels.create(5,"buyerzone.com|businessnewsdaily.com",false,function(){var a=document.createElement("span"),b=Math.floor(Math.random()*11E3);a.style.display="none";var c=document.location.protocol==="https:"?"https":"http";a.innerHTML='<iframe style="display:none" src="//ads.pubmatic.com/AdServer/js/user_sync.html?r='+b+"&p=46338&predirect="+c+"%3A%2F%2Fpixel.servebom.com%2Fpartner%3Fcd%3D"+b+'%26svc%3Dus%26id%3D5%26uid%3D"></iframe>';userSyncPixels._fragment.appendChild(a)});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

userSyncPixels.create(36,"creativebloq.com|buyerzone.com|newegg.com|businessnewsdaily.com",false,function(){var a=document.createElement("iframe"),c=Math.floor(Math.random()*11E3);a.style.display="none";var b=document.location.protocol==="http:"?"http":"https";a.defer=true;a.src=b+"://purch-match.dotomi.com/match/bounce/current?networkId=20077&version=1&rurl="+b+":%2F%2Fpixel.servebom.com%2Fpartner%3Fcb%3D"+c+"%26svc%3Dus%26id%3D36%26uid%3D$UID";userSyncPixels._fragment.appendChild(a)});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

userSyncPixels.create(45,"creativebloq.com|buyerzone.com|businessnewsdaily.com",false,function(){var a=document.createElement("script");a.async=true;a.type="text/javascript";a.src="https://ads.pubmatic.com/AdServer/js/userSync.js";a.onload=function(){PubMaticSync.sync({pubId:155494,delay:1E3,url:"https://pixel.servebom.com/partner?svc=us&id=45&cb="+Math.floor(Math.random()*11E3)+"&uid=(PM_UID)",macro:"(PM_UID)"})};userSyncPixels._fragment.appendChild(a)});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

userSyncPixels.create(32,"space.com|tomsguide.com|tomshardware.com|livescience.com|laptopmag.com|newsarama.com|imore.com|androidcentral.com|windowscentral.com",true,function(){var c="pixel.servebom.com",a=Math.floor(Math.random()*11E3),f="tmx_sync_"+a,b="qds0l";if(b===""||b.indexOf("$")===0)return;var d=document.createElement("span");d.style.display="none";var e=document.location.protocol==="http:"?"http":"https",b=b+".publishers.tremorhub.com",c=e+"://"+b+"/pubsync?redir="+e+":%2F%2F"+c+"%2Fpartner%3Fcb%3D"+a+"%26svc%3Dus%26id%3D32%26uid%3D%5Btvid%5D",a=document.createElement("iframe");
a.id=a.name=f;a.src=c;a.frameBorder=0;a.frameSpacing=0;a.scrolling="no";a.width=1;a.height=1;d.appendChild(a);userSyncPixels._fragment.appendChild(d)});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

userSyncPixels.create(17,"buyerzone.com|businessnewsdaily.com",false,function(){var b=document.location.protocol==="https:"?"https":"http",a=document.createElement("span"),c=Math.floor(Math.random()*11E3);a.style.display="none";a.innerHTML='<iframe style="display:none" src="'+b+"://bh.contextweb.com/bh/rtset?pid=558527&cb="+c+"&ev=1&rurl="+b+"%3A%2F%2Fpixel.servebom.com%2Fpartner%3Fsvc%3Dus%26id%3D17%26cb%3D"+c+'%26uid%3D%25%25VGUID%25%25"></iframe>';userSyncPixels._fragment.appendChild(a)});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

userSyncPixels.create(2,"buyerzone.com|businessnewsdaily.com",false,function(){var a=document.createElement("iframe"),b=Math.floor(Math.random()*11E3);a.style.display="none";var c=document.location.protocol;a.defer=true;var d="ssum.casalemedia.com";if(document.location.protocol==="https:")d="ssum-sec.casalemedia.com";a.src=c+"//"+d+"/usermatch?r="+b+"&s=181869&cb="+c+"%2F%2Fpixel.servebom.com%2Fpartner%3Fcb%3D"+b+"%26svc%3Dus%26id%3D2%26uid%3D";userSyncPixels._fragment.appendChild(a)});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

userSyncPixels.create(42,"buyerzone.com|businessnewsdaily.com",false,function(){var a=document.createElement("iframe");a.style.display="none";a.async=true;if(window.gdprUser&&window.__cmp)__cmp("getVendorConsents",null,function(b){a.src="https://sync.bfmio.com/sync_iframe?ifpl=5&ifg=4&id=Purch&gdpr=1&gc="+b.metadata+"&gce=1";userSyncPixels._fragment.appendChild(a)});else{a.src="https://sync.bfmio.com/sync_iframe?ifpl=5&ifg=4&id=Purch&gdpr=0&gc=&gce=1";userSyncPixels._fragment.appendChild(a)}});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

userSyncPixels.create(15,"buyerzone.com|businessnewsdaily.com",false,function(){var a=document.createElement("iframe"),c=Math.floor(Math.random()*11E3);a.style.display="none";var b=document.location.protocol;a.async=true;a.src=b+"//sync.adkernel.com/user-sync?zone=39660&r="+b+"%2F%2Fpixel.servebom.com%2Fpartner%3Fcb%3D"+c+"%26svc%3Dus%26id%3D15%26uid%3D{UID}";userSyncPixels._fragment.appendChild(a)});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

userSyncPixels.create(46,"buyerzone.com|businessnewsdaily.com",false,function(){var a=document.createElement("span"),b=Math.floor(Math.random()*11E3);a.style.display="none";var c=document.location.protocol==="https:"?"https":"http";a.innerHTML='<iframe style="display:none" src="//ads.pubmatic.com/AdServer/js/user_sync.html?r='+b+"&p=156007&predirect="+c+"%3A%2F%2Fpixel.servebom.com%2Fpartner%3Fcd%3D"+b+'%26svc%3Dus%26id%3D46%26uid%3D"></iframe>';userSyncPixels._fragment.appendChild(a)});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var partnerId=27;userSyncPixels.create(partnerId,"buyerzone.com|businessnewsdaily.com",false,function(){var a=document.createElement("iframe");a.style.display="none";a.async=true;a.src="https://px.powerlinks.com/user/identify?rurl=https%3A%2F%2Fpixel.servebom.com%2Fpartner%3Fsvc%3Dus%26id%3D"+partnerId+"%26uid%3D${USER}";userSyncPixels._fragment.appendChild(a)});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

userSyncPixels.create("19","",false,function(){var c=Math.floor(Math.random()*11E3),a=document.createElement("iframe");a.style.display="none";a.async=true;var b="assets.rubiconproject.com";if(document.location.protocol==="https:")b="secure-assets.rubiconproject.com";var d="11868",e="us-east";a.src=document.location.protocol+"//"+b+"/utils/xapi/multi-sync.html?r="+c+"&p="+d+"&endpoint="+e;userSyncPixels._fragment.appendChild(a)});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var partnerId=55;userSyncPixels.create(partnerId,"creativebloq.com|buyerzone.com|businessnewsdaily.com",false,function(){var a=document.createElement("iframe");a.style.display="none";a.async=true;a.src="https://cookie-matching.mediarithmics.com/v1/get_user_agent_id?dom_token=purch18";userSyncPixels._fragment.appendChild(a)});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

var partnerId=57;
userSyncPixels.create(partnerId,"creativebloq.com|buyerzone.com|businessnewsdaily.com",false,function(){var a=document.createElement("iframe");a.style.display="none";a.async=true;if(window.gdprUser&&window.__cmp)__cmp("getVendorConsents",null,function(b){a.src="https://pixel.advertising.com/ups/58164/sync?gdpr=1&gdpr_consent="+b.metadata+"&_origin=1&redir=true";userSyncPixels._fragment.appendChild(a)});else{a.src="https://pixel.advertising.com/ups/58164/sync?gdpr=0&gdpr_consent=&_origin=1&redir=true";userSyncPixels._fragment.appendChild(a)}});

});
} catch (e) {
console.error(e);
}
try {
tmntag_ready(function() {

(function(){document.body.appendChild(userSyncPixels._fragment)})();

});
} catch (e) {
console.error(e);
}
